### ISSUE TITLE
C# runtime stackoverflow crash

### ISSUE THREAD

**Issue by aienabled** [EsotericSoftware/spine-runtimes#1001]
I just noticed that this code:
```C#
currentTrack.MixTime = currentTrack.MixDuration = 0;
```
will throw a stackoverflow exception sometime later. And it's really hard to debug as it doesn't print the stacktrace (a common problem for stackoverflow exception).

I understand the code above might make no sense (and now I simply do `currentTrack.MixTime = 1;` and it works perfectly well) but still it would be better if Spine Runtime will throw a proper exception when this code is invoked. Or the stackoverflow bug must be located and fixed.

Regards!

**Comment by pharan** [comment]
Thanks for reporting!
This likely applies to all runtimes, not just spine-csharp.
We'll look into a good fix or warning, whichever makes sense.

My initial suspicion is that AnimationState isn't able to dispose of old playing animations (TrackEntry objects) because mixTime never got the chance to become > mixDuration.
https://github.com/EsotericSoftware/spine-runtimes/blob/c1538b113bbace55e858b589875b7b6395817898/spine-csharp/src/AnimationState.cs#L142

So when it comes time to apply the AnimationState, it recurses down all the previous undisposed TrackEntries with Apply calls until the sheer number of TrackEntries can't be handled.
https://github.com/EsotericSoftware/spine-runtimes/blob/c1538b113bbace55e858b589875b7b6395817898/spine-csharp/src/AnimationState.cs#L218-L220

Out of curiosity, what were you trying to achieve by setting both to 0? And under what conditions were you doing that?

'cause, on its own, setting both to 0 should be fine. It will just apply once and get disposed.
But if you set it every frame, or probably other conditions, it can probably cause some sort of undisposed-TrackEntry cascade.

**Comment by aienabled** [comment]
@pharan, sounds right. I'm glad to help. BTW, your deduction skills are great! 👍

> Out of curiosity, what were you trying to achieve by setting both to 0? And under what conditions were you doing that?

I did it every update frame by setting specific animation frame I want to display (depending on the game input (mouse position)). I set `currentTrack.TimeScale` to 0 and as a safety measure against mixing I've unadvisedly added this problematic line `currentTrack.MixTime = currentTrack.MixDuration = 0;`. It started lagging after a few seconds (it seems to be, as you wrote, "some sort of undisposed-TrackEntry cascade") and then crashing with stackoverflow (without any callstack, stackoveflow in C#/CLR is really hard to debug!). Because I knew this was the only change I quickly located the issue. All I needed was only `currentTrack.MixTime = 1`.

Regards!

**Comment by pharan** [comment]
The `currentTrack.TimeScale = 0` was correct for what you were trying to do.

`currentTrack.MixTime = currentTrack.MixDuration = 0;` is a weird thing to do in that case.
I mean, again, you could set it once.
But keeping that mix value, every frame, forever, for all TrackEntries ultimately means you're not letting them mix out. Which is also fine unless you also keep setting new animations and not letting those proceed. So if it wasn't a stack overflow that would cause a crash, you would be leaking memory until you stopped doing the above.

Could add a note to MixTime docs.
