### ISSUE TITLE
[unity] if you load ab file the spine animation not show

### ISSUE THREAD

**Issue by mustang2247** [EsotericSoftware/spine-runtimes#1035]
if you build "6 SkeletonGraphic" to AssetBundle file "skg.u3d", and then you load "skg.u3d" file and load scene "6 SkeletonGraphic", so the spine animation error.
the demo add: https://github.com/mustang2247/unityhotupdateflow.git
err:[png](https://github.com/mustang2247/unityhotupdateflow/blob/master/nope.png)

**Comment by missli93** [comment]
how did you solve the issue

**Comment by HaraldCsaszar** [comment]
@missli93  We are sorry that Pharan has not posted a text description back then when closing the issue.

I would assume the problem is that the shader or material is not included in the same asset bundle. You would then need to ensure that the material `SkeletonGraphicDefault`  is included in your scene, or in an asset bundle that is loaded before the skeleton.

Please look at these forum threads here:
http://ko.esotericsoftware.com/forum/AssetBundles-Pink-Shaders-Problem-in-Unity-5-4-1-7142
http://ko.esotericsoftware.com/forum/Spine-and-AssetBundles-6109

If the problem then still persists, please report again, including a reproduction project zip package, and we will open a ticket accordingly. Thanks!
