### ISSUE TITLE
[ue4] Support for version 18+

### ISSUE THREAD

**Issue by tmathews** [EsotericSoftware/spine-runtimes#1038]
Tried following the build instructions for the latest version. Doesn't seem to be supported. Is this being worked on? 

Also is it possible to get documentation added for building the UE4 project on Linux?

**Comment by badlogic** [comment]
UE 4.18 is supported. Could you expand on what's not working for you?

The spine-ue4 runtime is not platform specific. Please check out this UE4 wiki entry on how to build on Linux https://wiki.unrealengine.com/Building_On_Linux

**Comment by badlogic** [comment]
Argh, I forgot to commit the new functions in animation state. Fixing! See also http://esotericsoftware.com/forum/UE4-AnimationStart-delegate-not-firing-9541

**Comment by tmathews** [comment]
I've tried the installation process with both Windows and Linux and still cannot get them work. This is after the new commit you have made. When I open the project it asks to compile for a new version, which then it proceeds to attempt but says failed and asks to build from source.

Also when I generate project files I receive an error that I have brought up here: https://answers.unrealengine.com/questions/724973/generating-project-files-crashes.html

I believe this may have been closed prematurely.

**Comment by badlogic** [comment]
Could you please post all the errors you get?

**Comment by tmathews** [comment]
Here is the log output I get when opening the project on Linux. https://gist.github.com/tmathews/100ef2f7d7e7ab5fa5457db263e73a75

**Comment by badlogic** [comment]
Please also post the errors you got on Windows.

On Nov 13, 2017 6:30 PM, "Thomas" <notifications@github.com> wrote:

Here is the log output I get when opening the project on Linux.
https://gist.github.com/tmathews/100ef2f7d7e7ab5fa5457db263e73a75

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/EsotericSoftware/spine-runtimes/issues/1038#issuecomment-343994796>,
or mute the thread

**Comment by tmathews** [comment]
My mistake, I must have done something wrong before. It is working on Windows with with the latest commit to 3.6 now. I would appreciate any insight on the Linux issues above.
