### ISSUE TITLE
[Unity] IndexOutOfRangeException and Matrix stack full depth reached

### ISSUE THREAD

**Issue by lihaochen910** [EsotericSoftware/spine-runtimes#1086]
Unity Version:2017.2.*,2017.3.1f1,2018.1.0b10
Spine Runtime:spine-unity-3_6-2018-03-08.unitypackage

That's Very similar to #501 , When I try to preview an animation in SkeletonData.
![image](https://user-images.githubusercontent.com/11693880/37390477-31c60fc6-27a3-11e8-95bd-02eb139f8d41.png)
![image](https://user-images.githubusercontent.com/11693880/37390588-915d4c10-27a3-11e8-9283-03ccaa2b91b3.png)

SpineEditorUtilities.cs Line-1853
![image](https://user-images.githubusercontent.com/11693880/37390654-c809d062-27a3-11e8-8b62-1ad425d0576b.png)

**Comment by lihaochen910** [comment]
The skeleton.json file.
[skeleton.json.txt](https://github.com/EsotericSoftware/spine-runtimes/files/1810173/skeleton.json.txt)

**Comment by pharan** [comment]
Thanks for reporting and sending a repro case! This wasn't happening in our test skeletons with bounding boxes or other test skeletons sent to us.

There may be something else going on with your export but I'm still looking into it. For now, adding changes to the Spine-Unity editor code to prevent these strange cases from breaking Unity like that.

**Comment by pharan** [comment]
Nothing seems wrong with your export. It was just the editor code.

But note that Unity BoundingBoxFollower doesn't support weighted bounding boxes, because Unity's Physics, box2D itself doesn't support shape deformation. But you can still do manual collision checking with methods you'll have to write yourself.

You can apply the fix immediately in your project by using the latest code:
https://raw.githubusercontent.com/EsotericSoftware/spine-runtimes/3.6/spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs
Just replace your project's SpineEditorUtilities.cs with this.

This will also be included in the next unitypackage update.

**Comment by lihaochen910** [comment]
It works.
I will try not to use weighted bounding boxes.

I still have a question.
My bounding boxes (in Unity) do not change shape with the animations exported by the Spine editor.
Is this related to weighted bounding boxes? I have added the BoundingBoxFollower Component to the corresponding bounding boxes.

**Comment by pharan** [comment]
Unity's Physics and box2D itself doesn't support shape deformation.
