### ISSUE TITLE
[ue4] Crash when assigning skeleton data in unreal engine

### ISSUE THREAD

**Issue by supersaiyansubtlety** [EsotericSoftware/spine-runtimes#1133]
I've successfully built an unreal project with the spine plugin, but when following the instructions [here](http://esotericsoftware.com/spine-ue4#Adding-a-Skeleton-to-a-Level). After placing an empty character, adding a spine skeleton animation component, and assigning my atlas file, when I try assigning my skeleton data to the new component unreal editor consistently crashes. My atlas and json files are here: [skeleton.zip](https://github.com/EsotericSoftware/spine-runtimes/files/2157458/skeleton.zip)

**Comment by badlogic** [comment]
Thanks for reporting. I assume you are using the latest code from the 3.6 branch?

**Comment by badlogic** [comment]
@supersaiyansubtlety Your repro doesn't contain any images, so I can't import it into UE4. Could you update it?

**Comment by badlogic** [comment]
I can reproduce the crash with a dummy PNG. Looking into it.

**Comment by badlogic** [comment]
I've fixed the crash when loading errornous skeleton and atlas files. Instead of crashing when a skeleton file and an atlas file don't match, you will see an error dialog describing the problem. Please update to the latest code on the 3.6 branch for spine-ue4.

Your atlas file is missing a region called "Fore Arm/Bicep". The Spine UE4 plugin can't load those files. Please make sure you exported your skeleton correctly. If you continue to have issues, please post on the forum and Erika may be able to help with the export.

Thanks for reporting!

**Comment by badlogic** [comment]
This is now also fixed in the 3.7-beta and 3.7-beta-cpp branches.

**Comment by supersaiyansubtlety** [comment]
Thanks, the error message at least makes it easier to test if my animation data is working. I'm getting similar missing component errors for every animation I try to import, so I've posted my issue in the Esoteric Forum. 
Thanks again
