### ISSUE TITLE
[ue4] Switching skins behaves differently in Spine Runtime than in Spine App

### ISSUE THREAD

**Issue by calebgray** [EsotericSoftware/spine-runtimes#1135]
Behavior that I'd expect, as seen in Spine App:

1. Switch to "Skin B" with an image inside a "Skin Placeholder."
2. Skeleton rendered with an image inside "Skin Placeholder" parent.
3. Switch to "Skin A" with empty "Skin Placeholder."
4. Skeleton rendered without image inside "Skin Placeholder" parent.

Unexpected difference, as seen in UE4 Spine Runtime:

4. Skeleton is still rendered with image inside "Skin Placeholder" parent. (Instead of removing the image that only exists in the other skin.)

--

I'm not sure if this is expected behavior or not, but since it contradicts the WYSIWYG principle, I figured I'd at least bring it to your attention. Thanks! ^_^

**Comment by pharan** [comment]
It is expected behavior. But it's something that's currently under consideration as skin combination becomes easier in future versions.

What currently needs to be done when you switch skins is call `skeleton->setToSetupPose` and then call `animationState->apply(skeleton)`,  to make sure it's updated to all the latest attachments. I'm not sure if you're using blueprints or code, or if blueprints provides any of this, including the skin switching stuff.

**Comment by badlogic** [comment]
To achieve what Pharan outlined in UE4 blueprints, you can simply call the `SetToSetupPose` function your Skeleton (Animation) component. The next update will call the C++ side apply method internally.
