### ISSUE TITLE
[ts] [widget] Spine doesn't showed up when running example

### ISSUE THREAD

**Issue by m00nb0w** [EsotericSoftware/spine-runtimes#1140]
I'm trying to integrate spine with my react app. But when I run example.html in the spine-ts widget folder, it didn't work, it just showed up the inline animation. 
<img width="1440" alt="screen shot 2018-07-10 at 11 21 55 am" src="https://user-images.githubusercontent.com/22721579/42489146-ab4f617a-8433-11e8-9636-96d3f738e449.png">

Do I need to setup anything (I've installed TS and npm)?

**Comment by badlogic** [comment]
Could you be more specific?  Can you show the errors in the console of your browser?

You do not need NPM and TypeScript, you can just grab `spine-widget.js` from here https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-ts/build

**Comment by m00nb0w** [comment]
I'm currently using Chrome. This is not my project I just try to run the example file in spine-ts/widget

<img width="1440" alt="screen shot 2018-07-11 at 9 13 44 am" src="https://user-images.githubusercontent.com/22721579/42547127-c17f5556-84ea-11e8-94d1-426a7d2da106.png">

**Comment by badlogic** [comment]
Ah, you aren't serving the files via http but load them directly from the file on disk. That won't work due to Chrome's security model. Seeing as you are on macOS, you can do the following.

1. In the terminal, navigate to `spine-runtimes/spine-ts`, then issue this command to start a local server `python -m SimpleHTTPServer`. This will create a tiny web server locally serving the files of the directory you started it in.
2. In your browser, navigate to http://localhost:8000/widget/example/. You should see the below.

![http://libgdx.badlogicgames.com/uploads/vOK623MTDs.png](http://libgdx.badlogicgames.com/uploads/vOK623MTDs.png)

Let me know if this doesn't work for you.
