### ISSUE TITLE
3.7-beta-cpp branch TextureLoader::unload is not called

### ISSUE THREAD

**Issue by darkspace** [EsotericSoftware/spine-runtimes#1141]
unload isn't called from anywhere in this branch.  My app doesn't need it called because I manage the lifetime of textures outside of spine.  I guess (?) passing a callback to AtlasPage::setRendererObject would be sufficient for others.

**Comment by badlogic** [comment]
Good catch. Ideally, I'd be able to retain the old interface of `TextureLoader` including the unload method. I'll look into fixing up the API, cheers!

**Comment by badlogic** [comment]
Finally had some time to look into this. It turns out that `Atlas` had a bug. Up until my [last commit](https://github.com/EsotericSoftware/spine-runtimes/commit/0284abe548a190698bc6092d4749a461192fc736), `Atlas` had a method called `::dispose`, which makes no sense in the C++ context. That method would invoke the `TextureLoader::unload` method.

I moved the contents of the `dipose` method into the `Atlas` destructor, so `TextureLoader::unload` is now called properly on Atlas destruction.

Thanks for reporting!
