### ISSUE TITLE
Cocos2d-x / C / (possibly new C++ Runtime) Performance Issue with opacity zero

### ISSUE THREAD

**Issue by ForestRingGames** [EsotericSoftware/spine-runtimes#1145]
I think we found a possible performance improvement for the Cocos2d-x / C Runtime:

In SkeletonRenderer.cpp, there's a memcpy operation performed for every slot, copying its vertex data, etc. and only afterwards it is checked whether this slots opacity is 0 and therefore it doesn't need to be rendered.

Couldn't here the opacity check be performed first and only if the opacity is != 0 you'd copy over the vertices?

In the attached screenshot, you'll see some of the copy operations being performed at the top while at the bottom there's the check.

![image](https://user-images.githubusercontent.com/21338444/42758380-996d9e3e-8903-11e8-9541-4d451537da58.png)

**Comment by badlogic** [comment]
I've modified both the C and C++ runtimes accordingly, and made sure the engine integrations apply this trick. It should be noted that the color of an attachment is generally not changing, as it can't be animated. We still test for 0 alpha in case the user changes the attachment color programmatically.

**Comment by ForestRingGames** [comment]
@badlogic Thanks, interesting about the note - I wasn't aware. So setting a slot's alpha to zero did already avoid the extra memory allocations? Or was this also done in this change?

**Comment by badlogic** [comment]
Setting slot alpha to zero would still result in copying vertices. The
latest commits fix this.

On Jul 18, 2018 15:17, "framusrock" <notifications@github.com> wrote:

@badlogic <https://github.com/badlogic> Thanks, interesting about the note
- I wasn't aware. So setting a slot's alpha to zero did already avoid the
extra memory allocations? Or was this also done in this change?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/EsotericSoftware/spine-runtimes/issues/1145#issuecomment-405926536>,
or mute the thread
