### ISSUE TITLE
[cocos2d-x] 3.6.48 or 3.6.52 version, tint black had wrong display

### ISSUE THREAD

**Issue by huangwei1024** [EsotericSoftware/spine-runtimes#1158]
tint black setting in editor

![image](https://user-images.githubusercontent.com/667876/43893437-92bd1b3a-9c01-11e8-8046-a2e48af51888.png)

effect in editor, left is 3.6.52 (ok), right is 3.6.48 (wrong)

![image](https://user-images.githubusercontent.com/667876/43893458-a44954b8-9c01-11e8-89bf-779c13b9d732.png)

first, in 3.6.48 and 3.6.52 editor, the tint black are different effect, and the 3.6.52 editor version is right.

second, we use the newest branch 3.6 runtime source in cocos2dx to load the files, both of them are wrong display.

there are wrong in cocos2d-x. left is video which captured in 3.6.52 spine editor

![image](https://user-images.githubusercontent.com/667876/43893823-dd729d52-9c02-11e8-9368-3a6c6f16919c.png)

**Comment by badlogic** [comment]
Please send me the Spine project including images to contact@esotericsoftware.com

**Comment by huangwei1024** [comment]
ok，I sent yet, check your mailbox

**Comment by badlogic** [comment]
@huangwei1024 I've investigated this using the files you send me. The first two screenshots (comparison between 3.6.48 and 3.6.52) I can not reproduce in the 3.6.52 editor. The images seem to be from frame 71, which looks like this for me in the 3.6.52 editor.

![https://libgdx.badlogicgames.com/uploads/qPVMgQjl5o.png](https://libgdx.badlogicgames.com/uploads/qPVMgQjl5o.png)

I used this as a baseline and fixed the 3.6 cocos2d-x runtime (also fixed in 3.7-beta and 3.7-beta-cpp). Please update to the latest 3.6 branch commits and let me know if the behaviour still does not match your expectations. It looks exactly like in the editor now.
