### ISSUE TITLE
[ue4] Reimport not working or crashing

### ISSUE THREAD

**Issue by antidamage** [EsotericSoftware/spine-runtimes#1177]
Currently the spine asset types haven't been set up for reimport. Normally when you right-click on the main asset and choose "reimport" it should do what you'd expect.

That option hasn't been implemented however, which means not only deleting the old assets before reimporting them, but also deleting any blueprints that reference them as there seems to be some weirdness going on with the way the assets behave leading to broken references continuing to exist. For the same reason you also can't import and replace the existing assets.

Please look into this as it'd be an ENORMOUS help with the spline workflow in UE.

**Comment by badlogic** [comment]
Hm, I get a notification to re-import in UE4 when I update the file(s) the UE4 asset is based on. IpThanks for reporting!

**Comment by badlogic** [comment]
Hey @antidamage, thanks for reporting. This should be fixed with the commit above. Please pull in the latest changes from the 3.7-beta-cpp branch. Also make sure to copy over the latest contents of `spine-cpp`, as there was another fix for hot reloading, see #1180.

Note that the reimport only works if you change the .json or .skel file of a skeleton. Just changing the .atlas file will not work.

If your asset is inside the root folder of your UE4 project, or a subfolder of that folder, and you change a file, the UE4 editor will ask you to re-import. If your source asset file is outside that root folder, you can use the asset action -> reload menu item to reload.

Thanks for reporting!

**Comment by badlogic** [comment]
The fix for this was incorrect. Need to rework the way how we signal asset changes.

**Comment by badlogic** [comment]
Related crash http://esotericsoftware.com/forum/UE4-3-7-beta-cpp-re-import-crash-10975

**Comment by badlogic** [comment]
Closed in favor of #1246
