### ISSUE TITLE
[unity] BoundingBoxFollower forcefully adds Rigidbody2D component

### ISSUE THREAD

**Issue by jhett12321** [EsotericSoftware/spine-runtimes#1179]
The culprit is the AddSkin method in BoundingBoxFollower (called in OnEnable, and in editor), which forcefully adds a Rigidbody2D component if it does not exist (BoundingBoxFollower line 147, SkeletonUtility, line 82). This check does not search parents for a rigidbody.

Expected Behaviour: BoneFollower warning is presented to add a rigidbody component, unless rigidbody exists on self, or in a parent game object:

![Warning](https://i.imgur.com/dMXWQ3u.png)

Actual Behaviour: After a script compile, or exiting playmode, a rigidbody component is forcefully added to the collider's gameobject, ignoring any parent rigidbodies that may exist.

**Comment by pharan** [comment]
Interesting. Thanks for letting us know what you found. We'll look into the fix.

**Comment by pharan** [comment]
Note that even if you have a Rigidbody on the parent, as long as that collider's GameObject moves, Unity still recommends that it has its own rigidbody. This is because Box2D cannot have independently moving component shapes. Each thing that moves is its own Box2D equivalent rigidbody even if they are "parented" to each other.

**Comment by pharan** [comment]
https://github.com/EsotericSoftware/spine-runtimes/commit/6a8e1df1080883872c5210b5f8e956715138766e
