### ISSUE TITLE
Add code formatters for all languages and IDEs we use

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1205]
Define the coding style for each language and IDE we support/use, and if necessary, put IDE specific formatter files in the `spine-xxx` core runtime directories. Denote what is used below. Format all existing code accordingly.

- [x] spine-libgdx (libGDX formatter for Eclipse, can be imported into IntelliJ IDEA)

---
- [ ] spine-csharp (use the Visual Studio default, but configure it to use braces on same line all the time, check formatter into Git repository).
- [ ] spine-xna
- [ ] spine-monogame
- [ ] spine-unity
- [ ] spine-tk2d

---
- [ ] spine-c (Currently using default formatter of CLion)
- [ ] spine-cpp (Currently using default formatter of CLion)
- [ ] spine-sfml
- [ ] spine-cocos2d-objc
- [ ] spine-cocos2dx
- [ ] spine-ue4 (Currently using default formatter of Visual Studio)

---
- [x] spine-ts core (Visual Studio Code built-in TypeScript formatter)
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [ ] spine-as3 (Currently using default formatter of FDT)
- [ ] spine-starling

---
- [ ] spine-lua (No formatter used)
- [ ] spine-love
- [ ] spine-corona

**Comment by pharan** [comment]
I can't find the actual format used by VS 2017.
Not using the default C# formatting since Nate went with more Java-ish formatting for spine-csharp.

VS2017 seems to support the .editorconfig format but that doesn't encompass all the formatting rules you can set for C# in VS.

I'm not sure if this would apply in spine-unity, especially in older projects, as actual spine-csharp and spine-unity code would exist in in the same project/assembly as user's own game code. In some cases, the I guess the editorconfig would be ignored on their end. Need to look into where the files should go for the cases where spine-unity and spine-csharp can be its own project/assembly as in newer versions of Unity, if we're going with this format.
