### ISSUE TITLE
[unity] IOException

### ISSUE THREAD

**Issue by ledvinam** [EsotericSoftware/spine-runtimes#1260]
Hi we get IOException on skeleton data files. Can I please ask to close the stream when you finished reading it. Thank you, Marek. 

```
internal static void AddRequiredAtlasRegionsFromBinary (string skeletonDataPath, List<string> requiredPaths) {
				SkeletonBinary binary = new SkeletonBinary(new AtlasRequirementLoader(requiredPaths));
				Stream input = null;
				TextAsset data = AssetDatabase.LoadAssetAtPath<TextAsset>(skeletonDataPath);
				if (data != null) {
					// On a "Reimport All" the order of imports can be wrong, thus LoadAssetAtPath() above could return null.
					// as a workaround, we provide a fallback reader.
					input = File.Open(skeletonDataPath, FileMode.Open);
				}
				else {
					input = new MemoryStream(data.bytes);
				}
				binary.ReadSkeletonData(input);
				binary = null;
			}
```

**Comment by badlogic** [comment]
@ledvinam could you post the full stack trace here for completeness?

**Comment by HaraldCsaszar** [comment]
You seem to be using an already outdated package.
The bugfix was pushed yesterday: https://github.com/EsotericSoftware/spine-runtimes/commit/065c13f498b65e444fa7de944b96cdf44c0cdfd1
Package was made available here: http://esotericsoftware.com/spine-unity-download, spine-unity-3_7-2019-01-21.unitypackage

We will add explicit close calls nevertheless, since this was missing in terms of clean behaviour. However the error originated from a writable open call combined with the wrong != vs == null check.

**Comment by HaraldCsaszar** [comment]
Added using and finally-dispose guards around all stream instances, commit: https://github.com/EsotericSoftware/spine-runtimes/commit/edb2fbe8.
Will be included in next unitypackage.
