### ISSUE TITLE
[unity] Support .atlas file instead of .atlas.txt via ScriptedImporter

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1263]
Could additionally support .atlas extension instead of forcing .atlas.txt extension in Unity.

See https://docs.unity3d.com/2017.1/Documentation/Manual/ScriptedImporters.html

**Comment by badlogic** [comment]
`ScriptedImporter` is experimental still, even in 2019.x, so that's a no-go.

We also can't load `.atlas` and `.skel` files through the `AssetDatabase` but must instead rely on `File.ReadAllLines()` etc. This results in a huge amount of problems down the line. Even if we create `TextAsset` instances from the raw data manually, the `AssetDatabase` doesn't know about them, which makes a lot of code we have not work, as it relies on the assets being registered with the `AssetDatabase`.

It's thus with a heavy heart that we have to close out this fine issue.
