### ISSUE TITLE
[UE4]Unreal Engine 4.22 support

### ISSUE THREAD

**Issue by GitHub-NetFly** [EsotericSoftware/spine-runtimes#1318]
SpinePlugins is no longer compatible with UnrealEngine 4.22

**Comment by badlogic** [comment]
Fixed in both the 3.7 and 3.8-beta branch. We no longer depend on the RHI. The bigger issue was figuring out that the `IMPLEMENT_MODULE` macro changed. Where previously, the `I` prefix was removed by the macro when generating symbol names, that is no longer the case in 4.22. There was no mention of this in the changelog, no UBT warning, nothing. Love UE4 releases. The build system always breaks reliably.
