### ISSUE TITLE
[runtimes] Add Skin#addAttachments to all runtimes

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1323]
It appears we did not port the [`Skin#addAttachments(Skin)`](https://github.com/EsotericSoftware/spine-runtimes/blob/3.7/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/Skin.java#L69) method from the reference implementation to the other language runtimes. This makes creating custom skins harder than it should be.

- [x] spine-libgdx

---
- [ ] spine-csharp
- [ ] spine-xna
- [ ] spine-monogame
- [ ] spine-unity
- [ ] spine-tk2d

---
- [ ] spine-c
- [ ] spine-cpp
- [ ] spine-sfml
- [ ] spine-cocos2d-objc
- [ ] spine-cocos2dx
- [ ] spine-ue4

---
- [ ] spine-ts core
- [ ] spine-ts webgl
- [ ] spine-ts canvas
- [ ] spine-ts threejs

---
- [ ] spine-as3
- [ ] spine-starling

---
- [ ] spine-lua 
- [ ] spine-love
- [ ] spine-corona

**Comment by HaraldCsaszar** [comment]
For C#, `AddAttachments` is added as an extension method in the spine-unity runtime instead of spine-csharp:
https://github.com/EsotericSoftware/spine-runtimes/blob/3.7/spine-unity/Assets/Spine/Runtime/spine-unity/Modules/AttachmentTools/AttachmentTools.cs#L812

Decided Action: Methods shall be moved to spine-csharp on 3.8-beta branch (also don't forget to add CHANGELOG entry under c# and unity with “breaking changes”).

**Comment by badlogic** [comment]
We're going for the full implementation of this issue in the 3.8-beta branch https://github.com/EsotericSoftware/spine-runtimes/issues/841

Closing this issue in favor of #841.
