### ISSUE TITLE
[runtimes] Scale of -1 results in incorrect bone orientation

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1373]
**First issue:**

As reported on the forum:
http://esotericsoftware.com/forum/Unity-flipping-cause-missing-texture-12062

Reproduction assets for SkeletonViewer:
Reproduction package (1):
https://esotericsoftware.com/files/issues/1373_scale-1_incorrect_dog.zip
Reproduction assets originally posted on the forum.

Problem occurs in SkeletonViewer with reference implementation, branch 3.7. Also could be reproduced in Unity.

[Reproduction in SkeletonViewer]:
Problem could be reproduced with latest repository version of SkeletonViewer on 3.7 branch.
Steps to reproduce with repro assets (1):
1) Start SkeletonViewer
2) Open json asset of reproduction package (1).
3) Set Scale X slider to -100%. Now an incorrectly flipped mesh can be seen.

[Reproduction in Unity]:
Problem could be reproduced with runtime 3.7 (and 3.8-beta prior to skin-bones format changes).
Steps to reproduce:
1) create new empty scene
2) add dog asset
3) flip it in the editor via inspector of `SkeletonAnimation` component: Advanced -> Initial Flip X
4) In scene view and game view,  an incorrectly flipped mesh can be seen.

**Second Issue:** - **Fixed by commit https://github.com/EsotericSoftware/spine-runtimes/commit/ccc5b2f38b3e193d1bd6c679192086d1f0e53043.**
Reported here:
http://esotericsoftware.com/forum/ScaleX-issues-when-changing-root-rotation-in-spine-editor-12089

Reproduction package (2), should be easier to analyse:
Reproduction assets sent via email: FMfcgxwChJbtTtsFBPVFsgVkHldxdSWR
[end edit]

Steps to reproduce with repro assets (2):
1) Start SkeletonViewer
2) Open json asset of reproduction package (2).
3) Start animation `die`
3) Set Scale X slider to -100%. Now incorrectly rotating root bone (and character ) can be seen (it looks as if it still rotates to the original side). This is not the case when the character is not flipped.

**Comment by HaraldCsaszar** [comment]
![1373_ scale-1_incorrect](https://user-images.githubusercontent.com/32591206/59297717-317a0800-8c89-11e9-91e3-53ff2a4d23ee.PNG)
![1373_ scale1_correct](https://user-images.githubusercontent.com/32591206/59297718-317a0800-8c89-11e9-8791-12a9cb0dbe11.PNG)
![1373_ scale-1_incorrect_mirrored](https://user-images.githubusercontent.com/32591206/59297850-861d8300-8c89-11e9-9d0e-84ac7346112b.PNG)

Bottom-most image shows incorrect image, flipped in Photoshop.
Note that the bones of incorrectly displayed faces at the head area are facing the opposite direction after the Scale -1 change.

**Comment by HaraldCsaszar** [comment]
This forum posting here could be another occurrance of the same problem:
http://esotericsoftware.com/forum/ScaleX-issues-when-changing-root-rotation-in-spine-editor-12089

**Comment by NathanSweet** [comment]
Note ccc5b2f fixes skeleton scale using the root axes rather than the world axes.

For the dog project, the `Hairs Control Top` is the target bone of the constraint `Hairs Top TCS`, which is set to `World` (`Local` is not checked), `Relative`, and `Rotate mix 100%`. This means at the constrained bones' rotation will be their unconstrained rotation plus the world rotation of the target bone.

When the skeleton `scaleX` is 1, the target bone world rotation is 6.29. The constrained bones are adjusted to be their local rotation + 6.29.

When the skeleton `scaleX` is -1, the world rotation is 173.71 (== 180 + 6.29). The constrained bones are adjusted to be their local rotation + 173.71. This points them 180 degrees from the direction you want.

This is working correctly, as designed. The world rotation (used by constraints, returned by Bone `getWorldRotationX`, etc) is affected by the skeleton's scale.

The easiest fix for the dog project is to change the constraint to use the target bone's local rotation, not the world rotation, by checking `Local`. Another way to fix it would be to use the absolute world rotation, by unchecking `Relative`, which works because the constrained bones' rotation is set to match the target bone rather than added to it. With the absolute world rotation the constrained bones will all point the same direction, so the mesh may need to be bound to the bones differently.

**Comment by HaraldCsaszar** [comment]
Closing since both issues are resolved:
First issue by commit  https://github.com/EsotericSoftware/spine-runtimes/commit/ccc5b2f38b3e193d1bd6c679192086d1f0e53043.
Second issue turned out to be behavour as intended,
as Nate stated in above comment.

**Comment by NathanSweet** [comment]
We have updated the documentation with an explanation about using `Local` unchecked and `Relative` checked:
http://esotericsoftware.com/spine-transform-constraints#Options
