### ISSUE TITLE
[cpp] No way to check if Atlas loaded correctly

### ISSUE THREAD

**Issue by mikedmc** [EsotericSoftware/spine-runtimes#1393]
There's no way of telling if an atlas was loaded correctly. There's no error handling and no way of telling what happened if something goes wrong.

**Comment by badlogic** [comment]
There are two error scenarios when loading an atlas:

1. The data passed to the `Atlas` constructor has the wrong format. Since the data comes from the Spine Editor, we do not check for correctness.
2. The `TextureLoader` fails to load the texture for an atlas page. The loader is dependent on the engine or framework used for rendering. Error handling is thus delegated to that loader, as it has all the information to output useful error messages.
