### ISSUE TITLE
[unity] SkeletonGraphic (UI) issue

### ISSUE THREAD

**Issue by TowerCrow** [EsotericSoftware/spine-runtimes#1488]
More info here: http://esotericsoftware.com/forum/unity-SkeletonGraphic-UI-issues-12703

I've already emailed a reproduction Unity project to you guys.

**Comment by HaraldCsaszar** [comment]
The cause of your problem is due to SkeletonGraphic being limited to a single atlas texture (Unity's Canvas Renderer does not support multiple submeshes or materials). This limitation is documented on the updated spine-unity runtime documentation pages now:
http://esotericsoftware.com/spine-unity#SkeletonGraphic-Component
This section of the documentation pages also references export settings recommendations for SkeletonGraphic.

So you could either
a) switch from SkeletonGraphic to SkeletonAnimation, or
b) guarantee that all active attachments are on the same atlas page texture at any time. You could also repack a skin to a single
 atlas texture at runtime as described in this section: http://esotericsoftware.com/spine-unity#Setting-Skins
