### ISSUE TITLE
[unity] OutOfRange ( SdkVersion : updated 2020-05-14 )

### ISSUE THREAD

**Issue by gameproj** [EsotericSoftware/spine-runtimes#1678]
I am not good at English. Please refer to it.

First, I opened the spine JSON included in the project, and the version 3.8.76 is being used.
I updated to version 3.8 (updated 2020-05-14) while updating to URP yesterday.

But then I updated and ran it, and I found out that the file Asset\Spine\Runtime\spine-csharp\Animation.cs had a file.
OutOfRange error occurs in SlotIndex, BoneIndex, and ikConstraints.

After debugging, the index+1 became the last value for SlotIndex, BoneIndex, and ikConstraints.

I want to know why this problem occurs.
Do I have to export the same version 3.8 from the Spine again to use the 2020-05-14 version?

I fixed it as below, but since it's LINQ, the performance was not good.
Of course, the performance will be better if I change it to .LENGTH-1, but I want to know the cause.

![image](https://user-images.githubusercontent.com/6613017/82167594-47f7fd00-98f7-11ea-9ad5-caae4f1565b8.png)

**Comment by HaraldCsaszar** [comment]
I'm not sure I understand precisely which versions your setup is using.

Regarding your line:
> Do I have to export the same version 3.8 from the Spine again to use the 2020-05-14 version?
Is your skeleton `json` file exported from version 3.8? Which json file are you talking about, one of your own, or one of the example skeletons in `Spine Examples` of the spine-unity package?

So it will be important to know:
Did you export the problematic json file from Spine 3.8.76?
You are using the unitypackage spine-unity from 2020-05-14, is this correct?
Could you please attach the problematic `json` asset here as reference? Otherwise we will have no way of testing the issue you are describing.

Closing the issue for now until reproduction assets are submitted.
I will happily re-open the ticket when the required assets are available.
