### ISSUE TITLE
Can a FLUTTER version of the runtime library be added？

### ISSUE THREAD

**Issue by zhangyc** [EsotericSoftware/spine-runtimes#1781]
Can a FLUTTER version of the runtime library be added？

**Comment by badlogic** [comment]
I'm afraid we have no short or mid term plans to add Flutter support.

**Comment by guopeng1994** [comment]
any plans now?

**Comment by aytunch** [comment]
I guess @badlogic is working on it but i can't find it in this repo.

**Comment by badlogic** [comment]
It's in the 4.2 branch: https://github.com/EsotericSoftware/spine-runtimes/tree/4.2-beta/spine-flutter

Development has temporarily been halted due to a blocker in Skia which has just been resolved on their end:
https://github.com/flutter/flutter/issues/115919

The runtime is functional as is, but requires documentation and clean-up which is planned to be done in the next few weeks.

Integration with Flame is also working.

**Comment by aytunch** [comment]
This is great news. Thanks a lot. Can't wait until it is ready.
