### ISSUE TITLE
[ts] Setting local rotation produces unexpected results

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#1803]
Forum thread with videos of spine-ts behavior:
http://esotericsoftware.com/forum/bone-is-shakey-and-unstable-after-manual-bone-rotation-14822

Modified SimpleTest1.java:
```
state.apply(skeleton); // Poses skeleton using current animations. This sets the bones' local SRT.
skeleton.updateWorldTransform(); // Uses the bones' local SRT to compute their world SRT.

// Added:
Bone head = skeleton.findBone("front-bracer");
head.setRotation(head.worldToLocalRotation(180));
skeleton.updateWorldTransform();
```
Produces the expected results (front arm bracer always pointing toward screen left):
![](http://n4te.com/x/1182-rotation180.gif)
Given it works as expected with spine-libgdx, there may be something not working correctly with spine-ts. FWIW, Bone `worldToLocalRotation` looks right and I don't see what else could be wrong. First step would be to reproduce it in spine-ts using the user's code snippet.

**Comment by ShinhuPark** [comment]
Hello. I am the user who posted the forum thread. This doesn't seem like bug in spine-ts. When we update any bone upon world rotation, skeleton's worldtransform should be updated first.
Though this is recursive fuction using requestanimationfram(recursive function), so i was thinking it should be fine since the skeleton is updated at previous iteration.. I wonder why updateworldtransform() should be called both before and after the changing world rotation..
I added details about this on that forum thread. 
http://en.esotericsoftware.com/forum/bone-is-shakey-and-unstable-after-manual-bone-rotation-14822

Also related video :
https://youtu.be/3MhJC3B6HT8
