### ISSUE TITLE
[runtimes] ensure export.sh/runtimes.sh generates all data

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1825]
The `export.sh` and `runtimes.sh` scripts in `examples/export` currently do not generate all data, and delete data they shouldn't delete.

We've added a new example to `spine-libgdx`, demonstrating the use of frame-by-frame exports plus the meta data in texture atlases. These assets do not get exported by `export.sh`, nor copied by `runtimes.sh`. Instead, they are deleted from the target folder by `runtimes.sh`

The `spine-xna` backend has an example featuring a normal map for the raptor. This file is also not generated, and gets deleted by `runtimes.sh`. It is also unclear if re-exporting the raptor atlas will match the manually generated normal map.

**Comment by HaraldCsaszar** [comment]
>The spine-xna backend has an example featuring a normal map for the raptor. This file is also not generated, and gets deleted by runtimes.sh. It is also unclear if re-exporting the raptor atlas will match the manually generated normal map.

Normalmaps (as emission map, rim mask) need to be created/updated manually.
The above commit added `manual-maps` subdirs at `raptor` and `stretchyman` dirs, containing normal map, emission map, rim-mask. `runtime.sh` script now copies assets from this dir. These `manual-maps` directories need a manual update when the atlas or textures shall change, otherwise the previous consistent file-set from this dir is copied.
