### ISSUE TITLE
[unity] Spine Preferences `textureSettingsReference` setting changes between MacOS and Win

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1895]
As reported on this thread:
http://esotericsoftware.com/forum/SpineSettings-changing-win-mac-14733
Spine preferences `textureSettingsReference` setting changes between Mac and Win machines, detected as git file modification.
Could not yet be reproduced locally, but reported repeatedly.

Related to issue ticket:
https://github.com/EsotericSoftware/spine-runtimes/issues/1789

**Comment by abgtan** [comment]
Unity seems to re-initialize serialized values for assets in Assets folder whose source script reside in Packages folder when projects are newly opened, and this includes the SpineSettings asset (if it was added as a package).

This issue can be reproduced through these steps:
1. Start with a fresh Unity project, and add it to git the usual way.
2. Add Spine as a package (i.e. via Package Manager as a remote git package).
3. Change SpineSettings.asset (any value), then push the change to git.
4. Pull the Unity project from git to a brand new directory in the same machine, or a different machine altogether.
5. Open the project for the first time and let Unity do initialization and importation.

After the project opens, SpineSettings values will have been changed back to default by Unity, and this will count as a git file modification. This issue will repeat for every time Unity opens the project for the first time in a new location, or a new machine. This only happens when the source Spine runtime is in Packages and not when it is in the Assets folder, the same as where the SpineSettings asset is.

**Comment by HaraldCsaszar** [comment]
@abgtan Sorry for the late reply, thanks very much for sharing your findings!
Unfortunately I could not reproduce the behaviour that you described, using Unity 2022.1.17. Which Unity version are you using? Did you encounter these problems with the second project being on a PC or on a Mac?

I assume you have the settings file at the default location `Assets/Editor/SpineSettings.asset`, is that correct? Also I assume by hte above description you mean that you added the spine-unity packages via remote git URL, is that also correct?
Did you add other directories to git than `Assets`, `Packages` and `ProjectSettings`?

**Comment by HaraldCsaszar** [comment]
@abgtan If your setup is not different from what I have described above, could you perhaps please send us your `.git` directory of your reproduction project? You can send it as a zip package to contact@esotericsoftware.com, or attach a link to it here at the issue ticket.

**Comment by abgtan** [comment]
Hey sorry for the late response, I completely lost track of this issue. I dug further and found that my initial assumptions were wrong.

However, I found a related issue where if singleton scriptable assets were created such that it relied on the AssetDatabase knowing whether they exist or not, then if they were created in a static constructor, or in a method decorated with [InitializeOnLoadMethod], then when Unity Editor boots up in a fresh state, it could treat the asset as not existing yet, and recreate it as a result.

I looked at SpineEditorUtilities and the instance of SpinePreferences is now created in EditorApplication.delayCall. That should have been the fix for the above, but I'm not sure if this issue still persists since I couldn't replicate it anymore.

**Comment by HaraldCsaszar** [comment]
@abgtan Thanks for getting back to us and for sharing your findings! We will close this issue ticket as resolved for now, in case this issue re-occurs and can be reproduced, we're of course happy to re-open it again.

**Comment by sr4dev** [comment]
I've been dealing with this issue in my project for several years now.

I'd like to provide a reproduction project, but it's quite challenging since this issue occurs with very low probability.

I suspect the asset import order might be the key factor here. However, since Unity's architecture doesn't allow users to control the arbitrary order of asset imports, this makes creating a repro project even more difficult.

If asset import order is indeed the root cause, I think restructuring with ScriptableSingleton could be an effective solution:

```csharp
[FilePath("ProjectSettings/SpinePreferences.asset", FilePathAttribute.Location.ProjectFolder)]
public class SpinePreferences : ScriptableSingleton
```

Introducing ScriptableSingleton to SpinePreferences would require backward compatibility code to migrate the existing `SpinePreferences.asset` to ProjectFolder, but I've omitted that here for brevity.
