### ISSUE TITLE
[unity] Allow customizable fallback PixelsPerUnit setting for SkeletonGraphic

### ISSUE THREAD

**Issue by TheJustLink** [EsotericSoftware/spine-runtimes#1899]
Tags for google: big small size spine animation unity editor prefab
(people are looking for, but do not find a solution)

There is a problem when you need to edit UI in the prefab. The prefab does not contain root canvas with Canvas Scaler.
In the root canvas, using Canvas Scaler, I set PixelsPerUnit = 512 (default 100).
In prefabs, spine animations using incorrect PixelsPerUnit = 100. I want 512 (:

I'm using spine-runtimes v3.8.95 (the latest release)

To fix this, I change it manually in ```SkeletonGraphics.cs:356```:
```csharp
if (canvas != null) meshGenerator.ScaleVertexData(canvas.referencePixelsPerUnit);
```
To:
```csharp
if (canvas != null) meshGenerator.ScaleVertexData(512f);
```

It would be nice if PixelsPerUnit was taken out to some settings.
: )

**Comment by HaraldCsaszar** [comment]
Thanks for the input. We will add a customizable `Fallback Pixels Per Unit` parameter which will be provided in the Spine Preferences window.

> I'm using spine-runtimes v3.8.95 (the latest release)
There is no such version of the runtimes, if you mean the Spine Editor version, then you are not using the latest 3.8 version, which is 3.8.99.

**Comment by HaraldCsaszar** [comment]
While implementing this feature it turned out that in Prefab edit-mode there is always a parent Canvas used, which leads to `(canvas == null)` to not trigger.

However, a better solution exists: This prefab edit mode Canvas can be configured to your needs via `Project Settings - Prefab Mode - Editing Environments.` as mentioned here:
https://issuetracker.unity3d.com/issues/prefab-edit-mode-ignores-sprites-pixels-per-unit-setting
> "What can be done is that you can setup a scene with the canvas you want and assign this scene as UI Environment scene in Editor settings. "
Thus a fallback PPU Preferences setting should not be necessary.
