### ISSUE TITLE
[Unity] Improvements of Unity's SpriteAtlas support

### ISSUE THREAD

**Issue by CodeMasterYi** [EsotericSoftware/spine-runtimes#1900]
I have be trying runtime 3.8+, I found it support SpriteAtlas system of Unity. But it is useless, I think.
1. it doesnot support tight packing
2. it doesnot support late-binding
3. it refers the generate .png file and the spriteatlas file at one time, which makes it holds 2 pieces of the `same` texture in runtime.

**Comment by HaraldCsaszar** [comment]
Thanks for your input. We are aware that the SpriteAtlas support implementation is awkward, which is due to the very limited SpriteAtlas API which caused a lot of headaches and workarounds to get even a minimalistic implementation done.

Regarding your individual points:
1. it doesnot support tight packing
How should this work even in theory? Tight packing cannot be supported, as `RegionAttachments` could not be used at all, and `MeshAttachments` only if you are lucky that Unity packs no other Sprite inside your mesh bounds.

2. it doesnot support late-binding
This could perhaps be supported.

3. it refers the generate .png file and the spriteatlas file at one time, which makes it holds 2 pieces of the same texture in runtime.
This is a side-effect of the required workaround of the SpriteAtlas API not providing access to the packed texture in the Editor API. This could be improved by declaring the png texture as serialized for the Editor only (via `#if Unity_EDITOR`) and replaced by the generated SpriteAtlas texture at runtime.

As your comment is the first one requesting any improvements since the feature has been released about more than a year ago, we did not schedule the importance of this feature high enough to improve anything yet. Even more so, as Unity's API is making our work very hard in this regard.

Original implementation issue ticket for reference:
https://github.com/EsotericSoftware/spine-runtimes/issues/940

**Comment by HaraldCsaszar** [comment]
Item (3) above has been resolved by the above commit on the 4.1-beta branch. Material references to the generated .png atlas texture (required only in the Unity Editor) are removed in pre-build step when building your game executable.

A new 4.1-beta unitypackage is available for download.

**Comment by HaraldCsaszar** [comment]
Closing due to a lack of priority, despite point 2("it does not support late-binding") not being supported.
