### ISSUE TITLE
[unity] Cannot import assets from UPM packages?

### ISSUE THREAD

**Issue by raresloth** [EsotericSoftware/spine-runtimes#1924]
I noticed the AssetUtility purposefully skips importing assets that are located in UPM Packages. What's the downside to allowing this? We have a use case where we share common spine assets between multiple projects, and the assets live in UPM Packages. We develop the UPM packages alongside the base project, so we add new spine assets to the packages all the time, but the SkeletonData/Material assets are not generated because of these lines:

https://github.com/EsotericSoftware/spine-runtimes/blob/ba07ea9f91ee2ab1eb26c3f80d7bfbaca2bdab7a/spine-unity/Assets/Spine/Editor/spine-unity/Editor/Utility/AssetUtility.cs#L316

https://github.com/EsotericSoftware/spine-runtimes/blob/4.0/spine-unity/Assets/Spine/Editor/spine-unity/Editor/Utility/AssetUtility.cs#L330

**Comment by HaraldCsaszar** [comment]
Please note that there is another similar check here, in case you want to modify the code to your needs:
https://github.com/EsotericSoftware/spine-runtimes/blob/ba07ea9f91ee2ab1eb26c3f80d7bfbaca2bdab7a/spine-unity/Assets/Spine/Editor/spine-unity/Editor/Utility/AssetUtility.cs#L330

These two checks have originally been introduced since Unity 2019.1 issued errors upon adding the package via the package manager the first time, resulting in the following three errors per skeleton:
`Can not delete asset.  is not a valid path.`
`Couldn't add object to asset file because the MonoBehaviour 'stretchyman_Atlas' is already an asset at ''!`
`UnityException: Creating asset at path Packages\com.esotericsoftware.spine.lwrp-shaders\Spine Skeletons\StretchymanLWRP/stretchyman_Atlas.asset failed.
`

I will perform some testing whether this is perhaps no longer the case in more recent Unity versions.

**Comment by HaraldCsaszar** [comment]
Fixed on the 4.0 branch. Preprocessor branches have been added around the respective statements, allowing import of Spine assets from the `Packages` directory from Unity 2019.4 or newer (as the problem was verified in Unity 2019.1).

**Comment by raresloth** [comment]
Awesome, thanks for quick response to this!

**Comment by HaraldCsaszar** [comment]
Thanks for reporting!
