### ISSUE TITLE
[unity] BoundingBoxFollowerGraphic or BoneFollowerGraphic broken after spine-unity-4.0-2021-11-15

### ISSUE THREAD

**Issue by SyaoranChang** [EsotericSoftware/spine-runtimes#1999]
Hi,

The BoundingBoxFollowerGraphic and BoneFollowerGraphic was work fine in 4.0-2021-10-27,
but after upgrade to 4.0-2021-11-15, the script not work fine.
Can not auto detection Collider setting on spine.

The BoundingBoxFollowerGraphic setting:
![Snipaste_2021-12-09_18-26-28-2](https://user-images.githubusercontent.com/18550228/145379621-2f9ff2b6-fa83-4878-9af9-7338efd4a891.jpg)

4.0-2021-10-27 work fine.
![Snipaste_2021-12-09_18-24-03](https://user-images.githubusercontent.com/18550228/145379695-181f00ef-d0d2-44a1-a22d-0fbd05847737.jpg)

4.0-2021-11-15  was roken.
![Snipaste_2021-12-09_18-26-03](https://user-images.githubusercontent.com/18550228/145379826-0ad963f2-58e8-4316-8e80-b4857d433aa4.jpg)

**Comment by HaraldCsaszar** [comment]
Unfortunately we could not reproduce the issue, it is working as expected for us:
![BoundingBoxFollowerGraphic-working](https://user-images.githubusercontent.com/32591206/145437251-2e45cd73-cce6-409f-81a5-00e21f62f9d8.png)

Could you please send us a minimal reproduction Unity package that still shows this issue? You can also send it via email to contact@esotericsoftware.com (briefly mentioning this ticket URL so that we know the context).
Then we're happy to reopen it.

**Comment by HaraldCsaszar** [comment]
Thanks for sending the reproduction package, we can now reproduce the issue. We will get back to you as soon as we've figured out what's going wrong.

[Note: reproduction package received via email FMfcgzGllVqqBRkzdSwKFshbkldkFfTp]

**Comment by HaraldCsaszar** [comment]
Thanks for reporting. New 4.0 and 4.1-beta spine-unity unitypackages are available for download.
