### ISSUE TITLE
Skeleton Viewer sort animation by name, folder?

### ISSUE THREAD

**Issue by HaDH993** [EsotericSoftware/spine-runtimes#2002]
Hi,
I'm using Skeleton Viewer, but it it not sort animation name by folder like Spine Editor.
Can you modify and build new version sort animation by its name, folder?

**Comment by NathanSweet** [comment]
Sorting animations (and skins) by folder and name is surprisingly difficult. Besides sorting by folder, the Spine editor does it using "natural" sort order, which respects numbers within the folders and names. It even handles multiple numbers, like `attack12move3`. Becomes of the complexity, it's best to let the editor do this sorting.

The real bug is that the editor writes the animations (and skins) in an arbitrary order, and that is the order you get them from the Spine Runtimes API and in the Skeleton Viewer. It should write them sorted, so we've fixed that in 4.1.10-beta. Unfortunately we can't fix it in 4.0 because it would cause the exported data to change. Some people store the data in an SCM (like Git) so they can see the changes and this would add noise. Better to do it in the next version, 4.1.
