### ISSUE TITLE
Example projects use .skel files but not seeing a .skel option in Spine export?

### ISSUE THREAD

**Issue by residentruin** [EsotericSoftware/spine-runtimes#2026]
At some point the demo projects all moved to utilizing .skel files instead of the .json files they had previously used. A bit confusing considering the docs suggest .json is a better option than binary formats 

http://en.esotericsoftware.com/spine-binary-format

Having quite a bit of trouble getting this working so any help would be appreciated

**Comment by residentruin** [comment]
Can anyone point me to how i can convert these JSON files to skel?

**Comment by badlogic** [comment]
Where do the docs suggest that the JSON format is a better option than the binary format, because that would be wrong and needs fixing. The binary export is documented here: http://en.esotericsoftware.com/spine-export#Data

If you do not have the original Spine projects, you can import the JSON files as docmented here:
http://en.esotericsoftware.com/spine-import

To unpack atlas files, see the texture unpacker docs:
http://en.esotericsoftware.com/spine-texture-packer#Texture-Unpacker

Please use the forum at https://esotericsoftware.com/forum for questions. We generally use the issue tracker for bugs in the spine-runtimes.

**Comment by residentruin** [comment]
I apologize and will use the forum going forward. thank you for the quick response
