### ISSUE TITLE
[ts] Loading TextureAtlas

### ISSUE THREAD

**Issue by YakupTURKAN-pf** [EsotericSoftware/spine-runtimes#2029]
Hello, is loading texture atlas example from [this documentation](http://esotericsoftware.com/spine-loading-skeleton-data) page is out of date? I'm looking at the 4.0 branch right now 4.0.19 is the latest version according to branch.

[4.0 TextureAtlas constructor](https://github.com/EsotericSoftware/spine-runtimes/blob/b0de9cbfb67ea41b7a94aa88cbb30821ddbf3401/spine-ts/spine-core/src/TextureAtlas.ts#L38)
  
[3.8 TextureAtlas constructor](https://github.com/EsotericSoftware/spine-runtimes/blob/28727aff223afd731effbdee2b8f745211c95423/spine-ts/core/src/TextureAtlas.ts#L35)

**Comment by badlogic** [comment]
The documentation uses Java as the implementation language, that's why there are some differences. The API of TextureAtlas was modified slightly between 3.8 and 4.0 in spine-ts to make it more flexible. You first call the constructor with the `.atlas` file contents, then call `TextureAtlas.setTextures()` with an `AssetManager` to apply the textures.

That said, there shouldn't be a need to constructo the texture atlas manually. Use `AssetManager.loadTextureAtlas()` instead.

Please ask general usage questions on the forum at https://esotericsoftware.com/forum. The issue tracker is reserved for bug reports and feature requests.
