### ISSUE TITLE
Possible performance optimizations(specifically for Love2D)?

### ISSUE THREAD

**Issue by DreadPirateSergey** [EsotericSoftware/spine-runtimes#2061]
I'm developing game for phones, doing tests on Samsung S20. With about 4 spine entities game starts to lag on the phone(on PC it's okay with much bigger numbers). I tried to rewrite rendering part in C++ but result same, problem somewhere in rendering i think.

I wondering how generally one can optimize Spine implementation. What can be parallelized, maybe CPU-GPU communication could be done better etc. I basically checked love and sfml implementations and code logic is same there.
What Spine implementations has good performance on mobiles?

**Comment by badlogic** [comment]
If you are looking for a well-performing mobile implementation based on spine-cpp, then the spine-cocos2d-x runtime is what you want to look at. 

The Lua-based runtimes have been deprecated in Spine 4.0 and will no longer receive updates. Lua on mobile isn't the greatest performance wise anyways, especially on iOS where you can't use LuaJIT.

For a spine-cpp renderer, you want to ensure that you batch draw calls and avoid texture and shader switches as much as possible. spine-sfml doesn't do that, as it's geared towards desktop environments, and because SFML doesn't really provide good batching facilities. spine-cocos2dx does do that and performs well on mobile.
