### ISSUE TITLE
[unity] Runtime version 4.1 not backward compatible with 4.0 assets

### ISSUE THREAD

**Issue by stephen-funtra** [EsotericSoftware/spine-runtimes#2106]
We were using 4.0 runtime and have several assets exported with Spine2D 4.0 and these were working well.

We updated the runtime by updating `manifest.json`:
```json
{
  "dependencies": {
    …
    "com.esotericsoftware.spine.spine-csharp": "https://github.com/EsotericSoftware/spine-runtimes.git?path=spine-csharp/src#4.1",
    "com.esotericsoftware.spine.spine-unity": "https://github.com/EsotericSoftware/spine-runtimes.git?path=spine-unity/Assets/Spine#4.1",
    …
  }
}
```

However after updating the runtime to 4.1, the older assets no longer work. Aside from this error dialog:
![Screenshot 2022-07-05 210906](https://user-images.githubusercontent.com/102928325/177338466-e6644b20-4ee7-474d-9009-9d8c8fae7694.png)
We also have several of these errors in Unity's Error Logs:
```
Error importing skeleton 'Missions Icon': Skeleton data could not be loaded. Data version: 4.0.64. Required version: 4.1.
Please re-export skeleton data with Spine 4.1 or change runtime to version 4.0.
UnityEngine.Debug:LogError (object,UnityEngine.Object)
```

Is backward-incompatibility intended? Do we need to re-export all our existing spine assets using the new version? This is quite a pain for large projects with a lot of assets exported using older version of the software.

**Comment by HaraldCsaszar** [comment]
> Is backward-incompatibility intended?

Backwards compatibility is available on the project level, not on the (exported) assets level. 

>  Do we need to re-export all our existing spine assets using the new version?

Yes, it is necessary to re-export assets from the Spine Editor 4.1 when using the spine-unity 4.1 runtime (as it was for any prior version). That's why the error message in the dialog window and on the console are saying exactly that. We also explicitly state this in the documentation and forum:
http://esotericsoftware.com/spine-unity#Updating-the-spine-unity-Runtime
http://esotericsoftware.com/forum/Spine-Unity-4-0-to-4-1-Upgrade-Guide-17699
http://esotericsoftware.com/spine-runtime-architecture#Versioning

> This is quite a pain for large projects with a lot of assets exported using older version of the software.

Please note that we recommend automating the export, you should not perform manual export in large projects (and it's even recommended for small projects). You can find some helpful references in the first note box in the following documentation section:
http://esotericsoftware.com/spine-unity#Updating-the-spine-unity-Runtime
