### ISSUE TITLE
[unity] In the running case, the Spine animation should also be able to follow the TimeLine pause

### ISSUE THREAD

**Issue by HFX-93** [EsotericSoftware/spine-runtimes#2120]
When the spine animation is running, it does not suspend after TimeLine is suspended, which is a problem. I need the spine animation to also suspend TimeLine. I have seen the source code that you only processed the spine animation to follow TimeLine when it is not running. But running is what I also need
![image](https://user-images.githubusercontent.com/22762295/179970756-f09b3e97-2fd5-4ce2-9adf-b53ac51d6346.png)

**Comment by HaraldCsaszar** [comment]
The code branch that you show above is responsible for using a different mode how Timeline progression is applied to the `SkeletonAnimation` component. A separate edit mode pose branch is necessary here since the in-game code would not work in the Editor due to the different update structure. This code section is likely not relevant for your problem with pausing.

Could you please describe in more detail what code you use to pause the Timeline, which does not work as desired?
Which version of the Spine Timeline UPM package are you using?

**Comment by badlogic** [comment]
Closing this out. Will re-open if @HFX-93 provides more info.
