### ISSUE TITLE
[godot] Spine JSON auto-imports for whole project

### ISSUE THREAD

**Issue by aR-Dee** [EsotericSoftware/spine-runtimes#2134]
I noticed that Spine runtime has the JSON importer that automatically grabs all json's in project and creates .import files for them; is there a way to override it (tried to reimport files with "Import" and select "Keep file (No import), but it does not last, since on Godot restart it goes back to Spine JSON importer)? 

This behavior collides with other plugin's I use with the custom build of Godot with Spine runtime (in my case exactly it is a Dialogic plugin that does not handle .import files as it is not standard Godot behavior to create them for json's)

**Comment by badlogic** [comment]
Hm, do I understand correctly, that Dialogic also uses .json as resource files? That's mean the first editor import plugin that can handle the extension will b3 used for loading, which would be the spine-godot plugin, and not Dialogic, correct?

As a quick fix, you can use binary .skel skeleton files instead of the .json skeleton files. I'd recommend this format anyways due to smaller file sizes and faster loading speeds.

For a general fix, I'd have to check if the Godot editor API allows us to check if the .json file can actually be loaded and say "no" if it's no a valid skeleton file, passing the baton to the next plugin.

**Comment by meyaoigames** [comment]
Using .skel is not a fix since even without any Spine generated JSON file, using custom build of Godot Spine still auto imports ALL JSON existing in project as Spine skeleton. In the barebone project I test, there are no spine skeleton files present and the Dialogic character json files are still imported as such.

**Comment by badlogic** [comment]
Well, this can't really be fixed it seems. A file extension like .json can only ever be handled by a single plugin. If multiple plugins can handle .json, there's a first come, first serve mechanism. E.g. if the spine-godot plugin gets to see the .json file first and decides it's not a Spine .json file, then godot will just say "can't import" and not try another plugin that can also handle the extension.

I'm afraid I have no real solution for this at the moment and am waiting for input from the Godot devs.

**Comment by badlogic** [comment]
The "solution" for this problem is to use our own file extension for Spine JSON skeleton files. We are using `.spine-json` going forward. I have fixed up the 4.1 and 4.2-beta branches. I'm currently working on a Python script that can be used to convert an existing project and its resources to use the new extension.

**Comment by badlogic** [comment]
I've now also added a `convert.py` Python script. You can pass it a directory name containing your existing Godot project that still uses `.json` skeleton export files:

```
python convert.py /path/to/my/godot/project
```

It will then:
1. Rename all skeleton `.json` files to `.spine-json` and remove the `.json.import` files. Upon starting Godot the next time, the `.import` files will be recreated.
2. Scan `.tscn` and `.tres` files for external resources of type `SpineSkeletonFileResource` pointing to `.json` files. Those entries will be rewritten to point to the corresponding `.spine-json` files instead.

Before running the script, make a backup of your existing project files.
