### ISSUE TITLE
[unity] Build compile error after commit 01b8c06 due to unguarded `using UnityEditor.namespace`

### ISSUE THREAD

**Issue by AdrienVR** [EsotericSoftware/spine-runtimes#2222]
Hello,
We were referencing 
`"com.esotericsoftware.spine.spine-unity": "https://github.com/EsotericSoftware/spine-runtimes.git?path=spine-unity/Assets/Spine#4.1"`
and got this error in builds since commit **01b8c06800fbf7c444100c14389a87eccdd8c6e3**:

> `Library\PackageCache\com.esotericsoftware.spine.spine-unity@01b8c06800\Runtime\spine-unity\Components\SkeletonMecanim.cs(31,19): error CS0234: The type or namespace name 'Animations' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)`
> `Library\PackageCache\com.esotericsoftware.spine.spine-unity@01b8c06800\Runtime\spine-unity\Components\SkeletonRenderer.cs(54,19): error CS0234: The type or namespace name 'SceneManagement' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)`

We fixed it by rolling back to 
`"com.esotericsoftware.spine.spine-unity": "https://github.com/EsotericSoftware/spine-runtimes.git?path=spine-unity/Assets/Spine#ab28b77c70e3aa766be5bdb759d7aedac9fd0bde"` (which is the version tagged as release for 4.1 and will be of course safer for us)
Just wanted to inform you about this because you will probably want it to be fixed.

**Comment by HaraldCsaszar** [comment]
Thanks very much for reporting and very sorry for the troubles! This had indeed slipped through.

A bugfix has been pushed to the 4.1 and 4.2-beta branches, new unitypackages have been released accordingly as well.

Please note that in general, using a commit that was tagged with e.g. `4.1.00` is not recommended, as this is the _first_ commit since the 4.1-beta branch was changed to the release branch named 4.1 and is missing a lot of bugfixes. Thus we highly recommend to either using a fixed commit newer than that (now that could be commit 07b54ee18e407b40e576955e7613fc3088e9b4db), or change it back to using the latest 4.1 commit.
