### ISSUE TITLE
[godot] Seperate alpha not working correctly

### ISSUE THREAD

**Issue by GameJawnsInc** [EsotericSoftware/spine-runtimes#2225]
When you check the "Separate" option for a bone while keying alpha, the incorrect amount is applied. 

I've attached a zip with example projects. The testblob Skeleton has two animations called separate and not_separate, which are identical other than the "Separate" option selected. 

If you run the example Godot project, the buttons will loop either animation to demonstrate the issue.

Running the latest .exe from the readme and Spine 4.1.17

[GodotAlphaIssue.zip](https://github.com/EsotericSoftware/spine-runtimes/files/10421400/GodotAlphaIssue.zip)

**Comment by badlogic** [comment]
Thanks for the excellent repro! There was a bug in parsing skeleton binary files which has been fixed in both the 4.1 and 4.2-beta branch. New prebuilt Godot binaries are being build via [GitHub actions](https://github.com/EsotericSoftware/spine-runtimes/actions/runs/4016186945) and should be ready in about 3 hours.
