### ISSUE TITLE
Spine Haxe runtime

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2249]
- [x] Port to 4.1
- [x] Ensure compatibility with all OpenFL/Lime targets
- [x] Testing
- [x] Examples
- [x] Documentation
- [x] Release blog post & news

**Comment by jeremyfa** [comment]
Hey, very good news that an _officially maintained_ runtime for Haxe is in the works, thank you 🙏 

I maintain another Haxe game engine called Ceramic (https://ceramic-engine.com), and I also did setup this mostly auto-generated spine runtime for Haxe (from the libgdx/java one): https://github.com/jeremyfa/spine-hx (compatible with runtime 4.0) that I'm using with the engine.

I see in the current spine-haxe README that premultiplied alpha and 2-color tint (tint black) are not supported. Is that true for the whole runtime or just the current Starling renderer? The current implementation I use (the one above) does work fine with tint black when I use it with the renderer created for Ceramic, so I was wondering if that will be also possible with this new runtime, given that I support that in my own renderer?

**Comment by badlogic** [comment]
This is a limitation of the Starling renderer! It could possibly be alleviated, but I want to first focus on support for more frameworks like Ceramic or HaxeFlixel.

**Comment by jeremyfa** [comment]
I see, sounds good!

Feel free to ping me for anything related to Ceramic if needed!

The current spine (4.0) renderer implementation I use for Ceramic (which depends on the [spine-hx](https://github.com/jeremyfa/spine-hx) repo mentioned above) is there: https://github.com/ceramic-engine/ceramic/blob/master/plugins/spine/runtime/src/ceramic/Spine.hx and supports mesh, tint black and clipping. It's quite loaded with other features built on top of spine so you might find a lot of noise in it, but it does include the code that actually updates 2D meshes to display skeleton vertices etc...

I'll follow the evolution of runtime and the OpenFL/Starling implementation and might try to adapt the new runtime to my existing renderer for Ceramic at some point too (because I'll need to do it if I want to continue using newer Spine versions on the things I built on top of spine in Ceramic anyway), so you probably don't have to worry about Ceramic renderer much as long as the runtime itself works :)

**Comment by badlogic** [comment]
Had a quick look at the renderer. I think it should be possible to just switch to our spine-haxe runtime. The spine-haxe runtime itself is feature complete. There might be some API name differences, just because our spine-haxe runtime may be a bit more idiomatic. But other than that it is likely just a drop-in replacement for the spine-hx runtime you are using.

**Comment by jeremyfa** [comment]
Cool, I'll try it out when I have the time to test it then :)

**Comment by davidetan** [comment]
Release with this commit: c6775728b7c06d4b4c437f3622d7d1af97c4fd27

Blog post here: https://esotericsoftware.com/blog/spine-haxe-runtime-released
