### ISSUE TITLE
[unity] Create SkeletonDataAsset from .skel.bytes file at runtime (2.1.25)

### ISSUE THREAD

**Issue by IntroEvEivie** [EsotericSoftware/spine-runtimes#2286]
Help. How to import spin animation from local Skel, atlas, png files during work and run the animation? Version 2.1.25 is required, but there are no methods for importing older versions. Thx

**Comment by HaraldCsaszar** [comment]
Version 2.1.25 is extremely old. We highly recommend upgrading your Spine skeleton projects to a recent version (e.g. 4.1) and re-export the relevant assets from this version.

In general please post questions on the Spine forum instead of opening github issue tickets:
https://esotericsoftware.com/forum/
