### ISSUE TITLE
Spine Pixi Runtime

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2305]
See https://github.com/EsotericSoftware/spine-runtimes/pull/2299

TODO
- [x] Code review
- [x] Assets should be copied to the example dir via `examples/export/runtimes.sh`.
- [x] Add license header to all files where needed.
- [x] Formatting
- [x] Add JSDocs to public API
- [x] Check if batching actually works as intended, specifically with (dark) tint, and benchmark
- [x] Add support for PMA atlases if necessary
- [x] More examples
- [x] Documentation page
- [x] Release to NPM

**Comment by davidetan** [comment]
This https://github.com/EsotericSoftware/spine-runtimes/commit/0ac67cfbee498dd0bb9f4eff15ec909c31e283eb should address PMA.

**Comment by davidetan** [comment]
I've quickly tried Darktint and Pixi 8.

- Darktint doesn't seem to work. It must be manually enabled passing a DarkTintMesh factory, but doing so breaks PIXI.

- Pixi 8 doesn't work (probably expected since Pixi 7 is declard as a peer dependency). It simply fails to start complaining about dynamic requires.

**Comment by davidetan** [comment]
DarkTint actually works, but it has to be enable manually.
With 098fc0847, we changed this. DarkTintMesh is automatically used if at least a slot has dark color, so DarkTint renderer is registered by the runtime at import.
User can still decide to pass the default Mesh Renderer during Spine object creation.

**Comment by davidetan** [comment]
**Check if batching actually works as intended, specifically with (dark) tint, and benchmark**

Batching works, both normally and with dark tint.

Care should to set [`PIXI.Mesh.BATCHABLE_SIZE`](https://pixijs.download/v7.x/docs/PIXI.Mesh.html#BATCHABLE_SIZE) at a reasonable size (default is 100) because reasonable sized meshes in Spine easily reach this number.
For example, raptor example `body` has 314 vertices, and consequently breaks rendering in three batch unless `PIXI.Mesh.BATCHABLE_SIZE` is increased.

**Benchmarks**

On a 13-inch, 2018 MacBook Pro with:
- CPU: 2,3 GHz Quad-Core Intel Core i5
- GPU: Intel Iris Plus Graphics 655 1536 MB
- Memory: 16 GB 2133 MHz LPDDR3

Using `raptor-pro` - it uses default Mesh Renderer (no dark tint).
Setting `PIXI.Mesh.BATCHABLE_SIZE = 158;` (158 * 2 = 316 > 314 raptor vertices).

We can get:

- Up to 24 raport in 1 draw calls
- Up to 49 raport in 2 draw calls
- Up to 73 raport in 3 draw calls
- Up to 98 raport in 4 draw calls

Using `raptor-pro` - and passing the Dark Tint Renderer has the very same result as above.

**Blending modes**
Using blending modes interrupt batching as explained in [Pixi doc](**Benchmarks**).

**Caveats on using Dark Tint Renderer**
`DarkTintRenderer` of `spine-pixi` is a subclass of Pixi `BatchRenderer`. This implies that using it will break batching since webgl has to switch shader.
