### ISSUE TITLE
[react-native - three.js] WIP support

### ISSUE THREAD

**Issue by AlaricBaraou** [EsotericSoftware/spine-runtimes#2360]
I'm currently trying to use Spine in a react-native environment by using the three.js runtime. 

I published my code here https://github.com/AlaricBaraou/MiraiSenseiNative 
I'm trying to reproduce the [official three.js exemple ]( https://github.com/EsotericSoftware/spine-runtimes/tree/4.1/spine-ts/spine-threejs/example) and I believe I'm very close to succeed.

All textures, json and atlas seems to be correctly loaded when I log them, bones of the skeleton seems to have the same values as the three.js exemple. 
But for some reason the skeleton mesh never gets displayed. 

I have one warning at the moment that could be related which is 

> EXGL: gl.pixelStorei() doesn't support this parameter yet!

I assume this warning is coming from spine-ts\spine-webgl\src\GLTexture.ts update method but the three.js exemple don't seem to call this method ( I could be wrong, I'm still searching ) so I don't understand why my code would. And I don't believe it would cause the entire thing to disappear.

I know you don't officialy support react-native and that this is probably not the most optimal way to support it but I would really appreciate any help / pointers you could share to help me solve this.

Also happy to edit my code or anything to test your suggestions.

FYI, my next test would be to try with the most basic Spine file possible to debug more easily.

**Comment by AlaricBaraou** [comment]
I suspect that the issue comes from the fact that Spine is expecting a texture backed by a DOM Image I guess, and that in this polyfill, we use isDataTexture = true on the texture to force non-DOM upload for EXGL fast paths.

And doing so would do something that beak spine somewhere. I can't trace it, it's getting outside of my competences unfortunately.

**Comment by badlogic** [comment]
I'm afraid I have zero experience with React Native, much less in combination with ThreeJS. I don't even know how I could test/debug your project, so I'm unlikely to be able to give valuable advice here.

The `pixelStorei()` warning does indeed not come from the Spine code. The spine-threejs package doesn't depend on spine-webgl and doesn't do any direct WebGL calls. The only WebGL specific thing in spine-threejs is the pair of vertex and fragment shaders, which are pretty trivial and I would not expect them to be the culprit. That said, you could try instantiating the `SkeletonMesh` with a "draw every pixel in red" fragment shader. E.g.

```
         skeletonMesh = new spine.SkeletonMesh(
              skeletonData,
              (materialParameters) => {
                materialParameters.fragmentShader = `
                   void main(void) {
                     gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0)
                   }
                `;
              }
            );
```

That would rule out any issues with the texture upload and filter settings (e.g. not seeing anything might be due to mip maps being set to be used but not being generated, which might be a limitation of the WebGL implementation in Expo).



As with all things 3D API, the dreaded blank screen can have a gazillion causes.

**Comment by ultrafro** [comment]
I got stuck in the same place (black screen on react-native android, using expo and expo-gl). However, i saw the spine character rendering fine on react-native web.

- changing the shader's output colors did not work to make it not blank screen on react-native android. I even tried replacing the material with a basic material. This rendered a pure-green spine-character on the web, but still nothing on mobile

(in case this is helpful for someone else in the future) 
- i tried an example of a simple box on react-native-mobile using `InterleavedBufferAttribute`, and it did not render on Android, but rendered on web. When i tried `BufferAttribute`, the simple box rendered fine on both android and web. It looks like the `MeshBatcher.ts` relies heavily on `InterleavedBufferAttribute`, so I suspect that's why it's not rendering on react-native Android

**Comment by badlogic** [comment]
`InterleavedBufferAttribute` is indeed a requirement, specifically for performance. If that is not supported by expo-gl properly, then that appears to be a (pretty big) bug in expo-gl. Interleaved buffer attributes are a standard technique.

I'm afraid debugging expo-gl is a bit outside our area of expertise. Maybe you could submit your findings to them, specifically your simple box test.

**Comment by ultrafro** [comment]
thanks, I think I'll try to narrow down reproduction and forward to the folks at expo-gl

I was able to get spine-three-js working on ReactNative with Expo-GL (on Anrdoid, iOS, and web). It required changes to two files in this package:

Modifying https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-ts/spine-threejs/src/AssetManager.ts 
- changing the `loadTexture` method to use `ExpoTHREE.loadAsync`
- changing the `downloader`'s `downloadText` method to use expo `Asset` and `FileSystem`

Modifying https://github.com/EsotericSoftware/spine-runtimes/blob/8e200efdbb2c69e877d49a11dd02a1a73ac25195/spine-ts/spine-threejs/src/SkeletonMesh.ts
- use 3 `BufferAttribute`s instead of `InterleavedBufferAttribute` (position, color, uv)
- removing uses of `WebGLRenderingContext.DYNAMIC_DRAW;` (for some reason this would break rendering :/ )
- modifying `updateMeshMaterial` to set `isDataTexture` to `true`, and requiring that the `texture`'s `needsUpdate` gets set to `true`.

I'm planning on posting some code here as an example for those using RN

Out of curiosity, is there a plan to support RN via ExpoGL? It's canvas support has come a long way since this thread started

**Comment by AdamGerthel** [comment]
There's a proof of concept repository for RN available: https://github.com/Hau-Hau/react-native-spine-player

Haven't tried it myself

**Comment by Hau-Hau** [comment]
While my implementation is working, for sure it is not production ready. I don't had enough time to polish it. I would encourage to wait for official RN runtime or build RN runtime around new official iOS and Android runtimes.

Regarding integration of spine-threejs runtime with RN,; there has been done some progress in implementation of WebGPU standard on RN, so maybe in future it will enable new possibilities.
