### ISSUE TITLE
[TS/JS Webgl] Android sequences shader precision issues

### ISSUE THREAD

**Issue by Jeaper** [EsotericSoftware/spine-runtimes#2405]
Im running into spine-webgl > 4.1 issues on android devices. 
Image sequences "flicker" in position, vibrating

Issue dissapears if I modify spine-webgl shaders to be 
precision highp float;

Huawei mate 20 
Samsung galaxy s20
Samsung galaxy s8
Samsung galaxy s9+

(Might be Mali processor related?)

Not an issue in spine 4.0 for some reason

**Comment by Jeaper** [comment]
https://github.com/EsotericSoftware/spine-runtimes/assets/3511692/1849f50a-7bc6-474b-84cb-27477d514f67

**Comment by Jeaper** [comment]
We do have some new findings, and a "fix" for us.
One of our artists tried some different export settings in Spine and found this for the webp settings, which removed the flicker for us.

> 
> Resample:
> No Flicker = Bicubic
>      Flicker = Bilinear
> 
> Square textures:
> No Flicker = ON
>      Flicker = OFF
> 
> Alpha threshold:
> No Flicker = 3
>      Flicker = 2
> 
> Padding X:
> No Flicker = 5
>      Flicker = 4
> 
> Padding Y:
> No Flicker = 5
>      Flicker = 4
> 
> 
> Pretty sure these are irrelevant, but...
> 
> Limit memory:
> No Flicker = OFF
>      Flicker = ON
> 
> Pretty print:
> No Flicker = ON
>      Flicker = OFF
> 
> Combine subdirectories:
> No Flicker = OFF
>      Flicker = ON

**Comment by badlogic** [comment]
Wow, that's super weird, especially since it seems to depend on your texture atlas webp export settings.

I'm hesitant to set the precision to highp, as that puts more pressure on GPU side register allocation, which can detoriate performance especially on low- to mid-end mobile GPUs.

Since you found a solution for your issue, I'm closing this out. Thanks for reporting!
