### ISSUE TITLE
[unity] SkeletonRenderSeparator with CustomMaterialOverride might throw ArgumentNullException

### ISSUE THREAD

**Issue by alexfrosts** [EsotericSoftware/spine-runtimes#2435]
In some cases, when we separate spine, some created submesh renderers can have zero materials.
This leads us to `ArgumentNullException` during overriding initial materials with custom in MeshGenerator.TryReplaceMaterials method.
```
for (int i = 0; i < workingSubmeshInstructions.Count; i++) {
    var m = wsii[i].material;

    Material mo;
    // This would throw exception, cause dict can not get value by null key.
    if (customMaterialOverride.TryGetValue(m, out mo))
        wsii[i].material = mo;
}
```

This handles problem.
```
for (int i = 0; i < workingSubmeshInstructions.Count; i++) {
    var m = wsii[i].material;

    if (m == null)
        continue;

    Material mo;
    if (customMaterialOverride.TryGetValue(m, out mo))
        wsii[i].material = mo;
}
```

Or you can handle this somehow outer while working with instructions.

**Comment by HaraldCsaszar** [comment]
@alexfrosts Thanks for reporting. While it's not recommended to set up separation slots so that empty parts are output, empty parts may indeed result from disabling attachments at once valid parts.

We have released a bugfix, new spine-unity 4.1 and 4.2-beta unitypackages are available for download:
https://esotericsoftware.com/spine-unity-download
