### ISSUE TITLE
[spine-phaser] Issue loading spine assets

### ISSUE THREAD

**Issue by marioanloru** [EsotericSoftware/spine-runtimes#2449]
Loading spineAtlas with the following error:

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/14924057/8a4084ee-72b7-4919-9625-48aff9c679b8)
 
Phaser version: `"phaser": "^3.60.0"`
Spine phaser: `"@esotericsoftware/spine-phaser": "~4.1.31"`

It's a React with Redux project. Spine plugin is loaded into phaser game config object with:

```
import * as spine from "@esotericsoftware/spine-phaser"
...
plugins: {
        scene: [
            { key: "spine.SpinePlugin", plugin: spine.SpinePlugin, mapping: "spine" }
        ]
      },
...
```

And .skel and .atlas files are loaded inside "preload" phaser function as:

```
    this.load.spineBinary("spineboy-data", "spineboy-pro.skel");
    this.load.spineAtlas("spineboy-atlas", "spineboy-pma.atlas");
```

I took this images from https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-ts/spine-phaser/example/typescript/assets/spineboy-pma.atlas as the versions exported for these images should match as it is from 4.1

Using the phaser spine plugin instead of runtimes seems to work, but somehow I cannot make phaser spine runtime to work

**Code to reproduce the issue**: https://github.com/marioanloru/spine-phaser-test
Thanks for the help

**Comment by badlogic** [comment]
I have zero experience with React or Redux, so it's a bit hard for me to dig into your repro project. Where do I have to look?

**Comment by badlogic** [comment]
So, I got it to "run". The build system is so great, that I can not debug Spine related sources via source maps, as it refuses to work with the inline source maps we generate for our packages. Good stuff.

In any case, it seems like Phaser loads the assets from the wrong URL. Here it tries to load an image from a `text/html`, indicating that the server serving the assets returned bogus data. Funny, instead of a 404, the server just serves the index.html with status code 200.

<img width="714" alt="Screenshot 2024-01-16 at 10 50 21" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/df89fae7-2802-4ce0-8f2a-b8f44d8a4e48">

Looking into the dev console networking tab, it seems like `nullspineboy-pma.png` is being loaded, which obviously does not exist.

<img width="770" alt="Screenshot 2024-01-16 at 10 51 24" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/fe0921e8-73b7-42e5-be88-b6ce8bbb47ca">

The issue is in `SkeletonAtlasFile.onFileComplete`. It tries to construct a URL relative to the atlas file name to get the atlas PNG images. That fails, as you serve assets directly from the root directory.

<img width="685" alt="Screenshot 2024-01-16 at 10 58 06" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/e8b0733a-d702-4938-9135-7303eac2db00">

I've published a new package to NPM, version 4.1.51 that fixes the issue.

Possibly reconsider using React if all you are going to create is a game. Vanilla Phaser is plenty good enough for that, without all the ceremony and cruft introduced by React.

**Comment by marioanloru** [comment]
Thanks it works this way, but it still fails if I use `this.load.setPath('assets');`
So files needed are inside assets file as follows 
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/14924057/80a54fbf-bb8a-49fb-b610-1b1d2fb80442)
And it seems it is not correctly adding that path as it does not load the atlas file.
I am using react as I want my game to be inside a website, please if there is any other way of doing this by with vanilla phaser somehow I would love you pointing me to some kind of guide or doc

**Comment by marioanloru** [comment]
@badlogic

**Comment by kmizuki** [comment]
Is there any update on this?
I have the same problem.

**Comment by 48snowballs** [comment]
> uild system is so great, that I can not debug Spine related sources via source maps, as it refuses to work with the inline source maps we generate for our packages. Good stuff.
> 
> In any case, it seems like Phaser loads the assets from the wrong URL. Here it tries to load an image from a `text/html`, indicating

I'm having the same issue, can you please show me on how you made it works in your case?

**Comment by pablohastings** [comment]
I am also having this issue.  I did have it working but something change and I'm not getting the same error.
