### ISSUE TITLE
Using pack.json problem

### ISSUE THREAD

**Issue by semgilo** [EsotericSoftware/spine-runtimes#2456]
I expect to export images two separate parts, because I will custom body's material.
* one for body
* one for other

According the [pack](https://fr.esotericsoftware.com/spine-texture-packer#JSON-Configuration), I use pack.json instead  export,
the pack.json content is same with the packAltlas in the export.json 
`{
"stripWhitespaceX": true,
"stripWhitespaceY": true,
"rotation": false,
"alias": true,
"ignoreBlankImages": false,
"alphaThreshold": 3,
"minWidth": 16,
"minHeight": 16,
"maxWidth": 2048,
"maxHeight": 2048,
"pot": true,
"multipleOfFour": false,
"square": false,
"outputFormat": "png",
"jpegQuality": 0.9,
"premultiplyAlpha": true,
"bleed": false,
"scale": [ 0.5 ],
"scaleSuffix": [ "" ],
"scaleResampling": [ "bicubic" ],
"paddingX": 2,
"paddingY": 2,
"edgePadding": true,
"duplicatePadding": false,
"filterMin": "Linear",
"filterMag": "Linear",
"wrapX": "ClampToEdge",
"wrapY": "ClampToEdge",
"format": "RGBA8888",
"atlasExtension": ".atlas.txt",
"combineSubdirectories": true,
"flattenPaths": false,
"useIndexes": false,
"debug": false,
"fast": false,
"limitMemory": true,
"currentProject": true,
"packing": "polygons",
"prettyPrint": false,
"legacyOutput": false,
"webp": null,
"bleedIterations": 2,
"ignore": false,
"separator": "_",
"silent": false
}`

When I enable "stripWhitespaceX" and "stripWhitespaceY", the display result are wrong like this:
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/7121873/5d94bd5e-d718-4f31-b834-9976ac5cef93)

different attachment data 
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/7121873/d85358eb-06c1-492e-a283-27790bbc2401)

If you need further additional info, I will provide soon. I really appreciated if anyone can help me and point my mistakes out.

**Comment by HaraldCsaszar** [comment]
@semgilo Please use github tickets only for bugreports. For questions, please post on the official Spine Forum here:
https://esotericsoftware.com/forum/
Closing this issue ticket now to continue this discussion on the forum. This way others can also help or benefit from any insights.

Regarding your actual question: I'm afraid we need more information about your skeleton when you later write the posting on the forum. If possible, please also share the Spine project files including attachment images, so that we can reproduce any issues. Also please share which Spine Editor version you used that has caused the issue.

**Comment by semgilo** [comment]
Thanks for replying, but the forum has close posted function.  What can I do next?

**Comment by HaraldCsaszar** [comment]
You need to register at the forum, then you can post.

**Comment by semgilo** [comment]
Thanks for reply patiently. 
I have posted it. https://zh.esotericsoftware.com/forum/d/25512-using-pack-problem
