### ISSUE TITLE
[flutter flame] skin is not visible

### ISSUE THREAD

**Issue by casper7609** [EsotericSoftware/spine-runtimes#2471]
Hi, I'm trying to load skins for my spine object but it doesn't appear on the screen. Howerver, when I tried to load spine object with no skin, it worked. 
The code I tried is like below.

Future<void> loadSpine(TileType blockType) async {
    _spineTile = await SpineComponent.fromAssets(atlasFile: 'assets/spine/block.atlas', skeletonFile: 'assets/spine/block.skel');
   _spineTile.skeleton.setSkinByName('red');
    _spineTile.skeleton.setToSetupPose();
    _spineTile.scale = Vector2(GameConstants.tileScale, GameConstants.tileScale);
    await add(_spineTile);
}

Thank you in advance.

**Comment by badlogic** [comment]
I'm afraid I can't tell from the code what could be wrong. The code itself looks fine. Can you please share:

1. Your Spine project and images
2. Your .atlas, the corresponding .png, and .skel files

**Comment by casper7609** [comment]
[test.zip](https://github.com/EsotericSoftware/spine-runtimes/files/14503785/test.zip)
Here are the files. If you need more, please let me know :)

**Comment by badlogic** [comment]
@casper7609 sorry for the late reply.

The issue with your asset is that it doesn't have a default skin. When you instantiate a `SpineWidget`, it calculates a bounding box for the skeleton, given its currently active attachments. Since there's no default skin, there are also no attachments, resulting in a zero-size bounding box.

In cases where your skeleton doesn't have a default skin to deduce the bounding box from, you have to set a `BoundsProvider`, like in this example:

```dart
class SimpleAnimation extends StatelessWidget {
  const SimpleAnimation({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    reportLeaks();
    final controller = SpineWidgetController(onInitialized: (controller) {
      controller.skeleton.setSkinByName("red");
      controller.skeleton.setToSetupPose();
    });

    return Scaffold(
      appBar: AppBar(title: const Text('Simple Animation')),
      body: SpineWidget.fromAsset("assets/block.atlas", "assets/block.skel", controller, boundsProvider: SkinAndAnimationBounds(skins: ["red"]))
    );
  }
}
```

Here, I pass the "red" skin as the skin to use to calculate the bounds with.

**Comment by casper7609** [comment]
Thank you! I got it working now :) Just one thing, is there a way to create default skin in the spine editor? I did a bit of searching but couldn't find a way. An explanation I found was like "Spine generates default skin when exports". I tried to create default skin in the editor but the name was preserved.
