### ISSUE TITLE
[ts][pixi] Support for Pixi 8.x

### ISSUE THREAD

**Issue by furic** [EsotericSoftware/spine-runtimes#2531]
I understand this request may still come from a small segment of developers, but the performance [improvements](https://pixijs.com/8.x/guides/migrations/v8) in Pixi v8 are significant and would greatly benefit those of us using both libraries.

Here are a few necessary changes that I have identified:
- Use the package `pixi.js` instead of `@pixi/xxx`.
- Replace `this.updateTransform()` with `this.onRender = this._onRender.bind(this)`.
- Update `internalUpdate()` to accommodate new `Ticker` inputs:
```
protected internalUpdate (_deltaFrame: number, ticker?: Ticker): void {
	const delta = ticker?.deltaTime ?? Ticker.shared.deltaMS / 1000;
	...
```

EDIT:
Just found [`spine-v8` repo](https://github.com/pixijs/spine-v8) from Pixi.js, that ports spine-pixi runtime to Pixi.js v8.
At the time of writing, they are catching up to version `v4.2.45` already. I will keep an eye on this to decide if it's a good time to upgrade our projects.

**Comment by furic** [comment]
I can try to upgrade and create a PR if necessary.

**Comment by davidetan** [comment]
Pixi is quite used among Spine users, which is why we made `spine-pixi` an official runtime.
Adding support for Pixi8 is definitely on our roadmap.
However, we want to continue to support Pixi7 since it is still used a lot, and maybe 6 too.
Since its release is still quite recent, we are also waiting a little for the new version to be really stable.
We are also writing the official documentation for our website.

This is why we're taking a little more time to support the new version.
Having a PR to make Pixi8 work can definitely speed up the process.
We'll figure out how to support both versions.

**Comment by furic** [comment]
Just found [`spine-v8` repo](https://github.com/pixijs/spine-v8) from Pixi.js, that ports spine-pixi runtime to Pixi.js v8.
Closing this issue for now.
