### ISSUE TITLE
[spine-flutter] error run with spine_flutter

### ISSUE THREAD

**Issue by VanhnguyenX8** [EsotericSoftware/spine-runtimes#2562]
![Screenshot from 2024-06-27 09-40-14](https://github.com/EsotericSoftware/spine-runtimes/assets/86152761/4f01b104-be08-4457-bbd0-76c195c70643)
I get error when running version spine_flutter: ^4.1.1 and spine_flutter: ^4.2.29
"CMakeFiles/spine_flutter.dir/spine-cpp/src/spine/Skeleton.cpp.o:/home/mipix/.pub-cache/hosted/pub.dev/spine_flutter-4.2.29/src/spine-cpp/include/spine/Vector.h:162: more undefined references to `__assert_fail' follow
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed."

**Comment by VanhnguyenX8** [comment]
Here are my parameter values
![Screenshot from 2024-06-27 09-43-45](https://github.com/EsotericSoftware/spine-runtimes/assets/86152761/3aa2b645-c74d-40a3-82c2-410d904e3794)

**Comment by badlogic** [comment]
I'm having troubles reproducing this. Here's my flutter doctor output:

```
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale
    en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1.4)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

I've created a new Flutter project in IntelliJ IDEA, added the spine_flutter 4.2.29 dependency to it. The Android build tool version is 7.1.2. 

Next, I build for the Android emulator through the IDE (open emulator, select emulator as build target, hit run). That works as intended. Building a release APK for various target architectures (x86, ARM, ARM64) also works.

So I have no way to reproduce your issue. My guess is that something in your Android NDK may not be right. Sadly, that's not something I can debug on my end.

Please try running your project on the desktop instead of Android. If that works, please open our spine-flutter example project and try running it on Android.

I'll re-open this if I get more info.
