### ISSUE TITLE
[unity] Feature request: Better SpriteAtlas support

### ISSUE THREAD

**Issue by Gamer-XP** [EsotericSoftware/spine-runtimes#2589]
I was looking into a way to pack spine's textures together with my regular sprites, to improve performance. I tried using existing SpriteAtlas provider, but it seems to work really weird when I try to pack multiple different skeletons into single SpriteAtlas. There is no point of using Unity's SpriteAtlas if you're not going to pack all your stuff in it to begin with.
Why does it work in such a weird way to begin with? Can't it just reference actual Unity's Sprites as "region data" and update material's MainTex at runtime?

I was thinking of few ways to deal with it:
1. Pack original SpriteAtlas as a 1 big sprite as a part of SpriteAtlas. Need to just adjust material's settings to offset and scale UVs at runtime, and it will work. Easy to implement, should be no bugs since it will always be 1 texture in the end.
2. Use actual sprite as regions. Will allow to pack a lot of different skeletons more tightly, can load atlases with built-in addressables functions, plus you can use spine's sprite with regular SpriteRenderer.

Also, what I was looking to optimize actually require 2nd solution. We got a lot of buildings made with Spine. They are not animated normally, but still generate extra draw calls. I was looking into drawing them as regular Sprites when they are still, and swapping to Spine during animations. And 2nd solution is required there if I'm not to generate some extra textures.

**Comment by HaraldCsaszar** [comment]
@Gamer-XP In general please don't post feature requests as github issue tickets but instead post them on the forum as it's more difficult to discuss and share screenshots and other media here.

> I tried using existing SpriteAtlas provider, but it seems to work really weird when I try to pack multiple different skeletons into single SpriteAtlas.

What do you mean by "work really weird"? What undesired results did you get, or do you mean just the workflow (necessary steps) is weird?
If you got incorrect results, did you follow the documentation and requirements [here](https://esotericsoftware.com/spine-unity-assets#Advanced-Unity-SpriteAtlas-as-Atlas-Provider)?
Please note that e.g. enabling `tight packing` is not possible, as Unity creates an arbitrarily different tight mesh for each Unity Sprite.

> Can't it just reference actual Unity's Sprites as "region data" and update material's MainTex at runtime?

If you want to use single Unity Sprites and assign them at runtime as attachments, please check out the `Spine Examples/Other Examples/Mix and Match` and `Mix and Match Equip` example scenes.
Assigning single Sprites is not what the SpriteAtlas Atlas Provider is for. In general a Unity Sprite at runtime is a region in an atlas that is created behind the scenes, so you get pretty much the same result when creating the Unity SpriteAtlas yourself and add your required Sprites to it, and then use the SpriteAtlas Atlas Provider workflow.

In general please always describe what problem you are having that you want to solve, not how we could fix your attempted solution (see [XY problem](https://xyproblem.info/)).

> 1. Pack original SpriteAtlas as a 1 big sprite as a part of SpriteAtlas. Need to just adjust material's settings to offset and scale UVs at runtime, and it will work. Easy to implement, should be no bugs since it will always be 1 texture in the end.

Do you mean you want to treat the Spine atlas texture as a Unity Sprite, and then pack it alongside with other Unity Sprites to a larger Unity SpriteAtlas? Why would you want to do that? Note that it will not "always be 1 texture in the end", e.g. when having multiple atlas page textures.
Note that you can pack multiple skeleton's attachments to a single atlas (via multiple ways, e.g. by packing by folder structure), or repack things at runtime if you need to be more flexible and can't pre-fit them into a single atlas.

> 2. Use actual sprite as regions. Will allow to pack a lot of different skeletons more tightly, can load atlases with built-in addressables functions, plus you can use spine's sprite with regular SpriteRenderer.

See the mentioned example scenes above.

> I was looking into drawing them as regular Sprites when they are still, and swapping to Spine during animations. 

If this is the problem you're trying to solve, just use the `Apply Regions as Texture Sprite Slices` button at the AtlasAsset (see the documentation [here](https://esotericsoftware.com/spine-unity-assets#Texture-Atlas-Asset)) to create Unity Sprites for all your Spine atlas textures.
If we misunderstood your problem, please start a thread on the forum so that we can better help with any issues you're trying to solve.

**Comment by Gamer-XP** [comment]
> In general please don't post feature requests as github issue tickets but instead post them on the forum as it's more difficult to discuss and share screenshots and other media here.

Sorry, didn't know. Will respost this issue on the forum later.

> What do you mean by "work really weird"? What undesired results did you get, or do you mean just the workflow (necessary steps) is weird?

Issues I had with it:
1. It require a lot of steps to do. Like manually cutting every atlas into sprites, then switching import type from Texture to Sprite/Multiple.
2. Button to enter play mode does not exist it automatically. It does when I manually select atlas asset. Probably, a bug?
3. It seems to not use actual texture atlas because it generates some additional texture in assets? I didn't test how it looks in build, but I assume it may create some weird texture duplicates, especially when working with addressables.
4. Some skeletons look broken. Can this system handle name collisions between multiple skeletons? We got a lot of sprites with same names. I need to pack those skeletons into an atlas with thousands of unrelated sprites too.

> Do you mean you want to treat the Spine atlas texture as a Unity Sprite, and then pack it alongside with other Unity Sprites to a larger Unity SpriteAtlas? Why would you want to do that?

Mostly to decrease number of texture swaps in general, also because there are often empty spaces in main texture atlas which can be filled with spine skeletons.

> If this is the problem you're trying to solve, just use the `Apply Regions as Texture Sprite Slices` button at the AtlasAsset (see the documentation [here](https://esotericsoftware.com/spine-unity-assets#Texture-Atlas-Asset)) to create Unity Sprites for all your Spine atlas textures.

This will not solve the problem because it will either:
a) If sprites are not packed in SpriteAtlas - it will still break batches because of texture swap
b) Is sprites are packed: I will have same texture packed in the atlas, as well as original texture used by skeleton, ie texture is duplicated.

**Comment by HaraldCsaszar** [comment]
> Sorry, didn't know. Will respost this issue on the forum later.

Thanks for your understanding. It also helps other users which might have similar questions, they can then also benefit from any insights. Looking forward to your posting.

A side note before you post on Unity's forums instead of ours, it's [this forum](https://esotericsoftware.com/forum/).
