### ISSUE TITLE
[godot] Fix web template zip file name for 4.3 builds

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2627]
See https://esotericsoftware.com/forum/d/26807-godot-43-spine-runtime-web-export-error

**Comment by badlogic** [comment]
See https://github.com/EsotericSoftware/spine-runtimes/commit/77ab726b3fd801e903e1488b557447d6ba1eb080

**Comment by misaki-eymard** [comment]
Sorry for the delay in noticing this, but it turns out that we actually also need `web_debug.zip` and `web_release.zip` as before. These are required if `Variant - Thread Support` is enabled in the export configuration:
![Screenshot 2024-09-13 at 10 19 13](https://github.com/user-attachments/assets/060bb0fa-fd0f-426a-bdc1-21e01871e62e)

This option appears to have been added in Godot 4.3.
Reference URL: https://godotengine.org/article/progress-report-web-export-in-4-3/#backporting-the-single-threaded-feature-from-godot3x

**Comment by badlogic** [comment]
We actually need 4 variants:

- `web_nothreads_debug`/`web_nothreads_release`
- `web_debug`/`web_release`
- `web_dlink_nothreads_debug`/`web_dlink_nothreads_release`
- `web_dlink_debug`/`web_dlink_release`

These actually all require a separate build, not just a renaming of the artifact we generate at the moment, which is the `web_debug`/`web_release` variant.

Sigh.
