### ISSUE TITLE
[Unity] How to modify spine animation color??

### ISSUE THREAD

**Issue by lvchengyuan** [EsotericSoftware/spine-runtimes#341]
I can't modify color to a spine object,the material.color has no effect ..   only to modyfi the shader can make it,, but it seems  all object changes.. looks like sharedmaterial.color .

So. how to modify a spine object color?

**Comment by pharan** [comment]
Hello @lvchengyuan !

I hope you posted this question on the forum a long time ago.
It's always faster to get answers there.

To change the "spine object" color:
```csharp
GetComponent<SkeletonAnimation>().Skeleton.SetColor(yourColor);
```

Setting the material color is disadvantageous if you have several instances of that skeleton because materials are always pulled from the AtlasAsset and that material is always shared.

We'll look into how to make instance-level materials at runtime sometime.
