### ISSUE TITLE
Please put the supported editor version into the runtime readme

### ISSUE THREAD

**Issue by foofel** [EsotericSoftware/spine-runtimes#526]
Sometimes runtimes do not support the latest editor features. It would ne nice to have an overview which runtime supports which (editor) version.

**Comment by NathanSweet** [comment]
With 20 runtimes, this would be difficult to keep up to date. For most editor version releases, we'd have to change them all, otherwise it would look like they are outdated when they aren't. I agree we should be able to do something better though. It's only important to know when the runtime is not working with the latest, so we can have a status section for each runtime that either says, "Works with latest" or lists the last editor version it is compatible with.
