### ISSUE TITLE
[cocos2d-x] Support GPU side transform of vertices like in old runtime version

### ISSUE THREAD

**Issue by ShuraLiu** [EsotericSoftware/spine-runtimes#545]
I find that Spine is now using TrianglesCommands to render in cocos2d-x, but I don't think it's more efficient. When using TrianglesCommands, 2d-x will convert the node's position from local space to world space before drawing in every frame. So if nodes are using TrianglesCommands with the same texture and shader and their draw commands are adjacent in the command queue, they will be drawed together. In this way 2d-x reduces the drawcall. It's fine with Sprites and Labels because we usually use atlas for them and they have a few vertices to draw(usually 6 for each), and the position transform will not take much time. 
But in Spine it is an other thing. First the batching will only work when different spine nodes use the same file, which means the same texture and shader. Secondly when using mesh in spine, it will cause a lot of vertices to convert form local space to world space with CPU,  it's obviously not efficient.
So I think it's not efficient to use TrianglesCommands in Spine in 2d-x. I Strongly suggest you to use the old way, I think that is better.

**Comment by NathanSweet** [comment]
It is not generally a problem to pack multiple skeletons and other images into the same atlas to reduce draw calls. Developers know this and won't be surprised that Spine works the same way.

All of Spine's vertices are transformed on the CPU. I believe the old renderer did not transform the vertices by the scene graph node, which is incorrect since the node transform should affect the vertices. Also the old rendering code could not batch across scene graph nodes.

It is never a good idea to make assumptions on performance, even when it seems obvious. We can only make decisions on measured performance differences. Can you show a measured difference?

**Comment by ShuraLiu** [comment]
In the old way, 2d-x caculate the MVP martix for each spine node in CPU and send it to opengl uniform, and in shader it uses "gl_Position = CC_MVPMatrix * a_position" to caculate the gl_Position. In the new way, for TrianglesCommands,  2d-x multiply every vertex with MV martix in CPU, and send P martix to opengl uniform, and in shader it uses "gl_Position = CC_PMatrix * a_position" to caculate the gl_Position. For each spine node, the amount of calculation in CPU is the same in spine, but different in 2d-x. The old way cause one matrix multiplication for each node, but the new way cause much more(count of vertices). That' s why I think the new way is not efficient.
I'm sorry that I'm not good at English. I hope you can understand what I mean. Look forward to your reply.

**Comment by NathanSweet** [comment]
I understand. If your bottleneck was the number of draw calls, you would like the new renderer. If your bottleneck was the CPU, you would like the old renderer. We could make it configurable, so you could get the old behavior if you wanted that.

**Comment by badlogic** [comment]
We will not add GPU side skinning.
