### ISSUE TITLE
I Get OutOfMemory When I Import Spine to Unity

### ISSUE THREAD

**Issue by bantime** [EsotericSoftware/spine-runtimes#547]
export spine use binary, than import to unity,it crash at 
ReadSkin-> 
skin.AddAttachment( slotIndex , name , **ReadAttachment( input , skin , name , nonessential )** ); ->
case AttachmentType.weightedmesh: ->
float[] uvs = ReadFloatArray( input , 1 );->
float[] array = new float[n];

i print n is 1342177279

so i get exception,

but if i export use json,

it import to unity success,

Only this file error, other spine export use binary is success too,
 i don't know why!

runtimes:v2.4
unity:v5.3.4

**Comment by pharan** [comment]
The latest Spine-Unity release only supports 3.0.

The beta for 3.1 support can be found here: http://esotericsoftware.com/files/runtimes/unity/spine-unity-3_1-beta2.unitypackage

PR for the 3.1 code is here: https://github.com/EsotericSoftware/spine-runtimes/pull/543


More info here: http://esotericsoftware.com/forum/Noteworthy-Spine-Unity-Topics-5924

**Comment by bantime** [comment]
Thx, I Use beta for 3.1 support, it's import spine success!

**Comment by pharan** [comment]
@bantime You may have problems loading new binaries after 3.1.05 because of this: https://github.com/EsotericSoftware/spine-runtimes/commit/3a06b829cc81203ebeec996efad33e4bef6cc8c7

You either have to stick to your current Spine version or update your runtime and re-export all your binaries again. This will apply every time the binary format gets updated.
