### ISSUE TITLE
[Starling] Starling 2 & bug fixes

### ISSUE THREAD

**Issue by neuronix** [EsotericSoftware/spine-runtimes#558]
Hi,

Starling 2.0 is now officially released: http://gamua.com/blog/2016/04/starling-20/

Could you please release a new runtime for the 2.0 version? Daniel has prepared a migration guide: http://wiki.starling-framework.org/manual/starling_2_migration_guide and so far other frameworks have not run into much trouble upgrading

Could you also use the opportunity to tackle some of the open issues?
- https://github.com/EsotericSoftware/spine-runtimes/issues/508
- https://github.com/EsotericSoftware/spine-runtimes/issues/507 (Fixed since post)
- https://github.com/EsotericSoftware/spine-runtimes/issues/440 (Fixed since post)
- https://github.com/EsotericSoftware/spine-runtimes/issues/429

Kind regards,

Cameron

**Comment by israelazo** [comment]
+1

**Comment by rahulkamra** [comment]
+=1

**Comment by neuronix** [comment]
I updated the post to show that two issues have been fixed since I first posted. Thanks Nathan :)

**Comment by badlogic** [comment]
Working on this now. The migration guide is a bit thin on important differences regarding the low-level rendering APIs. It appears shader support has been removed completely and is now replaced by fragment filters, which are far less powerful. I'll keep digging, watch the as3-update-3.3.0 branch.

**Comment by neuronix** [comment]
Great news @badlogic ! You can always ask @PrimaryFeather I'm sure he'd be happy to help you pick up speed on the migration as well as give some tips for optimal performance with the new architecture.

**Comment by PrimaryFeather** [comment]
Yes, we're already in contact! :smile:

In a nutshell, shader support has actually been expanded, but the API definitely requires an introduction. This section from the manual shows the most important basics: [Custom Rendering](http://wiki.starling-framework.org/manual/custom_rendering)

**Comment by rahulkamra** [comment]
Awesome News . Cant want to migrate the code. Thanks a lot.

**Comment by badlogic** [comment]
Happy to announce that port to Starling 2.0 has been completed! See https://github.com/EsotericSoftware/spine-runtimes/commit/3de5fe4ea37c1c7d5de640d7b57760f828557ace

Due to Starling 2.0's general new awesomeness, we were able to remove quite a bit of code from the Starling runtime, while maintaining the old functionality.

I have not ported premultiplied-alpha and smoothing yet, will be done when i update the runtime to 3.3 (which is up next).

Closing this out. I'll handle the other two issues in their respective threads. Would welcome testing on your end (and if someone gets premultiplied-alpha working, let me know. See SkeletonSprite rendering method :))

**Comment by PrimaryFeather** [comment]
That's great news! Thanks a lot for your efforts, Mario.

As for premultiplied alpha: you probably don't have to do anything here. Starling 2 automatically recognizes if a texture uses PMA and adjusts its fragment shaders accordingly. In other words: everything is PMA, and everything is rendered equally.
