### ISSUE TITLE
[lua] RegionAttachment is missing path value

### ISSUE THREAD

**Issue by metaphore** [EsotericSoftware/spine-runtimes#689]
`AttachmentLoader` has parameter `path`, but it completely ignores it and as result all attachments have empty `path` fields after creation.

For example take a look at `RegionAttachment` function:
```lua
function self:newRegionAttachment (skin, name, path)
	return RegionAttachment.new(name)
end
```
Afterwards, nobody use "path" field and always obtain connected image by using attachment's `name` field.

**Comment by metaphore** [comment]
Perhaps this is more up to `SkeletonJson.lua`. Following the creation code for other attachment types, it looks like `path` should be set from here rather than from `AttachmentLoader`

**Comment by pharan** [comment]
I asked about this before.
The unused path parameter in the loader interface was for specialized uses. Someone was using it for a reasonable purpose, I forgot what but it had something to do with not using AtlasAttachmentLoader.

It just made its way to other runtimes (like spine-lua) because the runtime ports were made to be as uniform as the languages allowed.

You're not running into problems with it, right? Just a harmless extra param?

**Comment by metaphore** [comment]
I use this field in editor and just expect that it's present at runtime. I extract images from `ImageSheet` using this value (if present). Seems like someone just forgot to assign it inside `AttachmentLoader`, because other attachments (like `MeshAttachment`) have it.

**Comment by pharan** [comment]
The other runtimes actually don't have or need the path field on the attachment objects. They just use the passed path at load time to extract the correct image/region/UVs from the right source.

Not sure why spine-lua defines somethingAttachment.path it but never uses it.

I suppose its uses depend on each specific framework on top of spine-lua. I assume it would have logic to override the abstract AttachmentLoader interface which really does nothing. (I also assume the dummy functions are there because the lua language doesn't have java/c++/c#-like interface syntax.)

**Comment by badlogic** [comment]
I'm in the process of updating the Lua runtime to be compatible with the latest Spine version. In the process, I hope I can trim a lot of fat such as this. Stay tuned.

**Comment by badlogic** [comment]
This has been fixed.
