### ISSUE TITLE
[unity] SkeletonRagdoll2D.SetSkeletonPosition()

### ISSUE THREAD

**Issue by movAX13h** [EsotericSoftware/spine-runtimes#693]
Hello,

In my usecase (pinball with ragdoll character as ball, so most of the time it's a pure ragdoll and sometimes poses should blend in, imagine superman pose) the mix feature can not be used because the skeleton world position is not updated every frame and thus mix moves the character to the start position.

I've tried to update the skeleton position every frame using SetSkeletonPosition() in Update(), LateUpdate() and with custom logic to update only when a certain distance was covered but it seems like SetSkeletonPosition() is only made to be used before removing the ragdoll, like in the example scene.

The result is that the mesh gets deformed badly after some seconds. I've uploaded a video here to see it in action: https://www.youtube.com/watch?v=jKV-W1mMkKM
Pease note: This happens only if calling ragdoll.SetSkeletonPosition() in Update(), LateUpdate() like mentioned above. The normal ragdoll example works like expected but it's a different usecase.

I'm kind of lost on this so I'm asking if anyone could give me a little hint or had a similar usecase or a possible solution.

Thank you very much!

**Comment by pharan** [comment]
That's right. `SetSkeletonPosition` was made specifically in case you needed to un-ragdoll your skeleton, so it can unradoll in what looks like in-place rather than the spot where the colliders were first spawned. The mix field was designed to serve that un-ragdolling process.

I didn't quite catch what problem you were trying to solve here though by using SetSkeletonPosition and mix.

Note that many of the Spine-Unity modules, including SkeletonRagdoll(2D), are sample implementations you can freely copy, duplicate and adapt to your needs. If they handle the simple case you need, that's great, but they can't possibly handle all possible cases people can think of. This is the primary reason why all Spine runtimes were made source-available and user modifiable.

**Comment by movAX13h** [comment]
Thanks for the explanation. The problem comes from my usecase which does not allow to unragdoll at any point but still needs the mix functionality. Mix, as it is implemented now, requires the skeleton position to be updated to the "estimated" skeleton position (as you mentioned) so I tried to update the position every frame but that results in a destroyed mesh.

I guess I'm going to work on a modified SkeletonRagdoll2D class then that keeps the transform position where it really should be at all times - to allow blending between ragdoll and animations at every point. Since I don't know the innards of Spine too good yet, I was hoping for a hint. At the moment I think that double updates might cause the problem since the skeleton component has its own UpdateWorld mechanic but tinkering with that did not give any positive results yet.
