### ISSUE TITLE
[cocos2d-x] Animation doesn't work anymore

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#707]
See http://esotericsoftware.com/forum/Spine-animation-stopped-showing-up-urgent-7075?p=32547#p32547

**Comment by Fraggle** [comment]
I also have a very strange issue with the 3.4 runtime.
Some animation seems to show "old" triangles from another skeleton (like if the batch was not correctly resetted).

**Comment by Fraggle** [comment]
I have the feeling that it was caused by this commit: https://github.com/EsotericSoftware/spine-runtimes/commit/48c5b06676c10454e52eed53dbfff7d2d6a3ee5f#diff-052b0e6f0b0ca71f0cd92b6c2e78be25

**Comment by Fraggle** [comment]
I can confirm that if I revert to that commit e3cdea94a092f6ca77f36ed94832a26da5c8d6a7 (the one jut before the use of cocos2d auto-batch) then everything works ok.

**Comment by badlogic** [comment]
Thanks for the info. Do you have a repro for me? The existing samples
worked as intended.

**Comment by Fraggle** [comment]
Unfortunately no, i can reproduce it easily 100% of the time in our game but I cannot make a simple test case.

**Comment by badlogic** [comment]
Hrm, the change in that commit is the "official" way of doing batching nowadays. Without a repro it's going to be hard to fix it. Can you describe your setup that causes the issue to appear? Maybe I can repro it like that.

**Comment by Fraggle** [comment]
I think it has to do with rendering in render texture. We have a "filter" thing that will render our spine in rendertexture to apply an outline on them.
I'll try to investigate some more today and let you.

**Comment by Fraggle** [comment]
It's not rendertexture.. still looking into it.
It seems to happen if I have 2 of the same spine animation in a row (that are batched together).

**Comment by Fraggle** [comment]
We found the issue in our case, i'll try to explain, i think it's 100% reproductible with HEAD.

We create a spSkeletonData that is shared between multiple animation on screen (initWithData(skeletonData, false)). The skeleton data points to a spAtlas object but each animation has his own animationState.
Before the switch to use cocos batching, you used to manage your own buffers in SkeletonBatch and copy the vertices datas from the TriangleCommands.
But now, you are just pointing to the vertices data (from TriangleCommand::Triangle that are actually coming from the atlas datas) and thus the last animation to manipulate the vertices will affect all the animations. Actually, batching or not, this will happen, it was a side-effect of removing all your memcopy into buffers in skeleton batch.

So, we worked around it by creating each animation from scratch all the time, it means we are loading and parsing the files everytime. I couldn't figure out a way to reuse the skeleton data but have a different atlas object for each animation.
I also noticed on the way that SkeletonRenderer have 2 initWithFile... for json and none for binary. I refactored a little bit so this:
```
void SkeletonRenderer::initWithFile (const std::string& skeletonDataFile, spAtlas* atlas, float scale) {
    _atlas = atlas;
	_attachmentLoader = SUPER(Cocos2dAttachmentLoader_create(_atlas));

	spSkeletonJson* json = spSkeletonJson_createWithLoader(_attachmentLoader);
	json->scale = scale;
	spSkeletonData* skeletonData = spSkeletonJson_readSkeletonDataFile(json, skeletonDataFile.c_str());
	CCASSERT(skeletonData, json->error ? json->error : "Error reading skeleton data.");
	spSkeletonJson_dispose(json);

	setSkeletonData(skeletonData, true);

	initialize();
}

void SkeletonRenderer::initWithFile (const std::string& skeletonDataFile, const std::string& atlasFile, float scale) {
	_atlas = spAtlas_createFromFile(atlasFile.c_str(), 0);
	CCASSERT(_atlas, "Error reading atlas file.");

	_attachmentLoader = SUPER(Cocos2dAttachmentLoader_create(_atlas));

	spSkeletonJson* json = spSkeletonJson_createWithLoader(_attachmentLoader);
	json->scale = scale;
	spSkeletonData* skeletonData = spSkeletonJson_readSkeletonDataFile(json, skeletonDataFile.c_str());
	CCASSERT(skeletonData, json->error ? json->error : "Error reading skeleton data file.");
	spSkeletonJson_dispose(json);

	setSkeletonData(skeletonData, true);

	initialize();
}
```
became this:

```
void SkeletonRenderer::initWithFile (const std::string& skeletonDataFile, spAtlas* atlas, float scale) {
    _atlas = atlas;
	_attachmentLoader = SUPER(Cocos2dAttachmentLoader_create(_atlas));

    spSkeletonData* skeletonData = nullptr;
    
    if ( skeletonDataFile.find(".json") != std::string::npos )
    {
        spSkeletonJson* json = spSkeletonJson_createWithLoader(_attachmentLoader);
        json->scale = scale;
        skeletonData = spSkeletonJson_readSkeletonDataFile(json, skeletonDataFile.c_str());
        CCASSERT(skeletonData, json->error ? json->error : "Error reading skeleton data.");
        spSkeletonJson_dispose(json);
    }
    else
    {
        spSkeletonBinary* binary = spSkeletonBinary_createWithLoader(_attachmentLoader);
        binary->scale = scale;
        skeletonData = spSkeletonBinary_readSkeletonDataFile(binary, skeletonDataFile.c_str());
        CCASSERT(skeletonData, binary->error ? binary->error : "Error reading skeleton data.");
        spSkeletonBinary_dispose(binary);
    }

	setSkeletonData(skeletonData, true);

	initialize();
}

void SkeletonRenderer::initWithFile (const std::string& skeletonDataFile, const std::string& atlasFile, float scale) {
	spAtlas* atlas = spAtlas_createFromFile(atlasFile.c_str(), 0);
	CCASSERT(atlas, "Error reading atlas file.");
    
    initWithFile(skeletonDataFile, atlas, scale);
}
```

_but i don't like checking for filename extension so I will switch to your thing whenever you are done :)_

Beside the missing version for binary there, to me there is an issue on your side because nothing prevents us to use it the way we did and we didn't except it to behave like that.

I hope this helps, let me know if you need more details.

**Comment by badlogic** [comment]
Thanks a ton for all the info. You are absolutely right that this needs to
be fixed on our end. I'll try to come up with something. I believe there's
a PR by a user that may fix it.

**Comment by badlogic** [comment]
I believe this PR actually fixes the issue when sharing data between applications. I'll merge it manually with the latest master in a bit, please give it a try when you find time https://github.com/EsotericSoftware/spine-runtimes/pull/712/files

**Comment by badlogic** [comment]
I've applied #712 (and #716) now. Please let me know if this fixes your issue.

**Comment by badlogic** [comment]
Closing this out, as the PR seems to have fixed the issue in my repros. Please let me know if it fixes it on your end as well.
