### ISSUE TITLE
[unity] BoundingBoxFollower.valid build compilation warning

### ISSUE THREAD

**Issue by AndreyPostelzhuk** [EsotericSoftware/spine-runtimes#717]
`BoundingBoxFollower.value` variable is used only inside `UNITY_EDITOR` define. If project uses `warnaserror` directive then building process will fail.

**Comment by pharan** [comment]
That's a reserved keyword in C#.
Where did you find `BoundingBoxFollower.value`?

**Comment by AndreyPostelzhuk** [comment]
@pharan 
> Where did you find BoundingBoxFollower.value?

Class `BoundingBoxFollower` line 50: [here](https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-unity/Assets/spine-unity/Modules/BoundingBoxFollower/BoundingBoxFollower.cs)

> That's a reserved keyword in C#

You mean `warnaserror`? It's an directive in `smcs.rsp` file. We marked some warnings as errors to force developers avoid them.
Example of `smcs.rsp` file:
```
-define:DEBUG
-warnaserror:414;649;114;219;168;162;
```

**Comment by pharan** [comment]
line 50 defines `bool valid`

Good catch though. Seems pretty useless since it's also private. Might as well be a local in the only method that uses it.
You can just define bool valid in the same line that sets it: https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-unity/Assets/spine-unity/Modules/BoundingBoxFollower/BoundingBoxFollower.cs#L131
Then remove the object field.

**Comment by AndreyPostelzhuk** [comment]
I've already fixed that bug locally. I've created this issue only for reason that good library shouldn't yields compilation warnings.
P.S.
Unused private field yields a compilation warning. `warnaserror` directive makes from compilation warning compilation error. And yes. After that build fails.

**Comment by pharan** [comment]
Thanks. Should be fixed pretty soon.
