### ISSUE TITLE
Mesh support in Canvas?

### ISSUE THREAD

**Issue by Skeptron** [EsotericSoftware/spine-runtimes#750]
Hi all!

I can't make the meshed examples work in Canvas mode (meshed sprites don't appear at all, others are displayed correctly). Is it normal? Should I give this feature up in canvas mode, or is it a bug?

Thanks!

(For the record, I used the raptor example (spineboy was displayed but not the raptor), and stretchyman (who wasn't displayed at all).

**Comment by badlogic** [comment]
Hi,

I assume you set `spine.canvas.SkeletonRenderer.useTriangleRendering = true` before rendering? Without it, mesh attachments will just be ignored.

That being said, the canvas triangle renderer is highly experimental and is known not to work well in some browsers due to problems in the rendering engine of these browsers (Safari, IE, I'm looking at you). I would not recommend using this feature but instead switch to the WebGL renderer instead.

**Comment by appsolutegeek** [comment]
Hi @badlogic, when you state to use the webGl renderer, which property is this ?

So leave triangleRendering = false, but do we need to enable another property to get the mesh to render.

I seem to be going round in circles :-) 

Is there something we can do in spine to export it, so that meshes are not needed and would be lighter on the client (html canvas) ?

Also I am using a phaser spine implementation and although it works well for all the examples that it ships with, any mesh spine files, it fails to render.

I was wondering if we can export and squash the mesh :-) Probably not the right terminology, but I think you get what I mean.

Thanks in advance

**Comment by badlogic** [comment]
Hi Ian,

I'm afraid I'm not familiar with the pixi.js Spine integration. The
author(s) are super capable and very responsive, so my first suggestion is
to ask on their tracker abut broken meshes. Provide one or more export
files and they should be able to fix it.

As for simlifying meshes on export from Spine: I'm afraid that is not
possible. If you don't want meshes, you simply shouodn't use them in your
Spine project.

Finally, regarding WebGL vs. Canvas: spine-ts has multiple backends. One is
for plain old Canvas, which gives you the best browser support, but can't
do meshes properly. The other uses a WebGL enabled canvas and WebGL to
render. This supports all features, but doesn't work in older versions of
IE (anything <= IE10 iirc). It's not a setting in spine-canvas, but a
separate implementation, in spine-webgl. Check out the samples in the
spine/webgl folder.
