### ISSUE TITLE
[c][cocos2d-x] Optimize runtime

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#767]
There might be some potential for optimizing spine-c and spine-cocos2dx. Use the profiler, Luke.

**Comment by badlogic** [comment]
See also http://esotericsoftware.com/forum/cocos2dx3-x-runtime-performance-compare-7632

**Comment by ForestRingGames** [comment]
@badlogic 
We have done some more profiling in the past week, since our game is getting closer to release and Spine is our bottleneck at the moment. We've also discussed the performance issues with fellow Cocos2d-x/Spine devs and we're not the only ones having performance problems. I've also put their insights into this post.
Our game highly relies on using hundreds of Spine Skeletons at once (see [Video](https://youtu.be/90Kl_BLr6KQ?t=66), every Tower and Unit is a Spine Skeleton), hence optimizing the performance of spine-cocos2dx and spine-c could boost our performance a lot. But on to the fun part: 

## Profiling

We profiled with the Xcode Time Profiler and also with the CCProfiler of Cocos2d-x (inserting time meassuring code). In this screenshot, we're animating 150 spine skeletons on an iPad Pro which results in 85% CPU usage. The idle CPU usage (only cocos2d-x) is 20%. 

<img width="873" alt="bildschirmfoto 2017-02-08 um 14 41 58" src="https://cloud.githubusercontent.com/assets/21338444/22739647/c863f230-ee0c-11e6-9800-c0a56a71866c.png">

Here's a list of suggestions for optimizations:

## **Reduce memory allocations when adding drawing commands**

SkeletonRenderer and SkeletonBatch are issuing a lot of tiny memory allocations when drawing instead of collecting them into a larger chunk of memory and then submitting this to CCRenderer.

SkeletonRenderer adds the triangles like this:

```
batch->addCommand(renderer, _globalZOrder, attachmentVertices->_texture->getName(), _glProgramState, blendFunc,
			*attachmentVertices->_triangles, transform, transformFlags);
```

And SkeletonBatch performs many memory allocations for every of these calls. According to our profiling, calls of this function alone cause ~20% (of the 85%) CPU usage as of now. The comments in the code are taken from jpoag from this thread: http://de.esotericsoftware.com/forum/cocos2dx3-x-runtime-performance-compare-7632


```
void SkeletonBatch::addCommand (cocos2d::Renderer* renderer, float globalZOrder, GLuint textureID, GLProgramState* glProgramState,
                                BlendFunc blendFunc, const TrianglesCommand::Triangles& triangles, const Mat4& transform, uint32_t transformFlags
                                ) {
    // We don't know what order or size we are getting attachments, or if the currently allocated verts are the right size, so...
    if (_command->triangles->verts) {
        free(_command->triangles->verts);
        _command->triangles->verts = NULL;
    }
    
    // malloc every frame
    _command->triangles->verts = (V3F_C4B_T2F *)malloc(sizeof(V3F_C4B_T2F) * triangles.vertCount);

    // copy every frame
    memcpy(_command->triangles->verts, triangles.verts, sizeof(V3F_C4B_T2F) * triangles.vertCount);
    
    _command->triangles->vertCount = triangles.vertCount;
    _command->triangles->indexCount = triangles.indexCount;
    _command->triangles->indices = triangles.indices;
    
    _command->trianglesCommand->init(globalZOrder, textureID, glProgramState, blendFunc, *_command->triangles, transform);
    renderer->addCommand(_command->trianglesCommand);
    
    // let's create a long command chain 'cache', although we aren't certain that every frame we will use every command
    if (!_command->next) _command->next = new Command(); 
    _command = _command->next;
}
```

In the end the performance impact of this is even higher though, since the CCRenderer has to iterate through all the tiny little triangle commands that were sent to it and copy them over to the actual render buffer. 

### Profiling Results 

**Adding the commands**
<img width="1223" alt="bildschirmfoto 2017-02-08 um 16 19 07" src="https://cloud.githubusercontent.com/assets/21338444/22743396/61141110-ee1a-11e6-9799-f35d88321ac3.png">

**CCRenderer processing the commands**

<img width="1639" alt="bildschirmfoto 2017-02-08 um 16 50 11" src="https://cloud.githubusercontent.com/assets/21338444/22744804/cd92fb18-ee1e-11e6-98cc-f1191ec563b6.png">


## **spAnimationState_apply**

spAnimationState_apply takes another big portion of the performance. As this is further away from cocos2d-x rendering pipeline and closer to the Spine internals, I'm not quite sure what could be optimized here (yet). I'm also not sure if this fruit is as low hanging as reducing the memory allocations. Please have a look into this to see if we can get some more performance here.

### Profiling Results 

**Overview**
<img width="1213" alt="bildschirmfoto 2017-02-08 um 16 18 23" src="https://cloud.githubusercontent.com/assets/21338444/22743512/ad5c6efa-ee1a-11e6-8386-c03868e96a33.png">

**Detail**
<img width="1217" alt="bildschirmfoto 2017-02-08 um 16 31 53" src="https://cloud.githubusercontent.com/assets/21338444/22743974/273caaf4-ee1c-11e6-9f7e-aca1f688b81d.png">

## **spSkeleton_updateWorldTransform**

According to the profiling results in the previous section this function takes ~6% of the total CPU usage. I'm not sure if the function itself can be optimized, there's lots of math going on here, so it might be worth a look. 
The function is calculating the world transform for every bone, even if the bone does not need it this frame. Though in our game (and probably in many others), not all bones of all skeletons are changing all the time, hence a dirty flag could save performance. @badlogic, I know that we've talked about it and that you didn't like the idea back then - though I wanted to add it to the list ;)

## **Culling**

It looks like there is no culling applied at the moment. Elviss Strazdins (@elnormous) has added this functionality in his version of the Spine-runtime for his own game engine. You can check it out here:
https://github.com/elnormous/ouzel_spine/blob/master/src/SpineDrawable.cpp

He's also only calling `spAnimationState_apply` and `spSkeleton_updateWorldTransform`when the skeleton is visible. For culling he's using the bounding box and he does recalculate the bounding box when drawing (and iterating through the bones anyway).

This is not a feature that we need for our game at all - but I'm adding it here since it may be useful for others. If it will be added, it would be cool to be able to deactivate it (like Culling for sprites in cocos2d-x can be deactivated) to save performance in non-scrolling games like ours.

**Comment by badlogic** [comment]
Thanks for the data, you put a lot of effort into this!

Culling is something that is somewhat game dependent, and easy enough to add on top of the Spine API. I think we won't add that as core functionality.

There aren't any low-hanging fruit in animation state & timelines at the moment.

The renderer is the best place to add optimizations. However, we can't commit to a timeline, and if your game is due for release soon, you may have to get your hands dirty optimizing the batcher yourself.

**Comment by liuyi** [comment]
All items are small, so use frame animation instead skeleton animation would be better.

**Comment by badlogic** [comment]
I've now commited the new batching mechanism to the 3.6-beta branch. I'm afraid this is as good as it gets for the moment. I removed all runtime allocations (save for resizing buffers, which will stop once the buffers are big enough to hold all the data necessary for a frame). I can't get rid of the memcpy to transfer UVs to the vertices. And there aren't any optimizations I can do on the skeleton update side.

We'll likely not backport this to 3.5 as the 3.6 release is imminent. It should however be simple to get this working in the 3.5 branch in your own fork of the runtime should you have to stay on 3.5.

**Comment by ForestRingGames** [comment]
Thanks for taking the time to do this! Too bad that you can't do more on it, but I won't complain :D I did some profiling on it and it seems like the CPU utilization is reduced by 5-10%, which is great! 

If I find some more ways to enhance the performance, I'll let you know.
