### ISSUE TITLE
[c] 3.5.x potential issue with animation switching back to setup pose.

### ISSUE THREAD

**Issue by Fraggle** [EsotericSoftware/spine-runtimes#789]
Hello,

In the 3.5.x runtime if we setAnimation() and then it ends, and we do nothing more, should the skeleton stay as it is or should it snap back to the setup pose ? From my understanding of the [documentation](http://fr.esotericsoftware.com/spine-applying-animations#Empty-animations) 

> When an animation is finished (see TrackEntry trackEnd) and no animations are queued for the track, the track is cleared and skeletons are left in their last pose. It may be desired to use setEmptyAnimation or addEmptyAnimation to mix the skeletons back to the setup pose, rather than leaving them in their previous pose. A mix time of zero can be used if the change needs to be abrupt.

and [the forum](http://fr.esotericsoftware.com/forum/Set-AddAnimation-Behaviour-bugged-7384), it’s only if i add another animation on the same track that unkeyed stuff should snap back to the setup pose, am i correct ?

If so, then i think there is a bug in the c runtime : it seems that if we setAnimation() and do nothing, everything will snap back to the setup pos (position, rotation, alpha, etc..) except the visibility. My hope is that the visibility is the right one and the other types of keys the wrong ones.

I attached a example : in the animation, we have a red and a blue square. Both are visible in the setup, the blue is alpha 50% the red is fully opaque.

In sequence "idle_1", we rotate and fade out the red square but we keep it's visibility "on". When we play this sequence, at the end, the red square snap back in place, rotation etc.. and fully opaque again => I expected it to stay exactly where it was.

In sequence "idle_2", we rotate and fade in the blue square and we finally switch it's visibility "off". When we play this sequence, at the end, the blue square snap back in place, rotation etc.. but stay hidden (visibility off) => I expected it to stay exactly where it was.

Can you please look at it and at least tell me if that's a bug or not ? I can understand it might take time to fix but just for my sanity (and removing the need for us to find workarounds) I really need to know if it's a bug or not.

Thanks,

Sebastien

[test-case.zip](https://github.com/EsotericSoftware/spine-runtimes/files/625042/test-case.zip)

**Comment by NathanSweet** [comment]
The big difference with 3.5 is that animations no longer leave the skeleton in the last state when the animation was applied. When 3.5 was first released, there were 2 ways an animation could be left in the last state an animation was applied: `clearTrack`/`clearTracks` or `trackEnd`. Shortly after the 3.5 release, we changed how `trackEnd` works so that when the `trackEnd` time is reached, the skeleton is reset to the setup pose rather than be left in the last pose from the animation that is no longer going to be applied. This leaves only one way for a skeleton to get stuck in the last animation applied state: `clearTrack`/`clearTracks`.

I apologize that our documentation was slightly out of date and did not reflect the recent `trackEnd` change. We've now updated the documentation:
http://esotericsoftware.com/spine-applying-animations#Empty-animations
http://esotericsoftware.com/spine-api-reference#TrackEntry-trackEnd

If you are struggling with how to keep changes to your skeleton state across multiple animations, you may want to review this recent discussion:
http://esotericsoftware.com/forum/3-5-Attachments-And-Mixing-7398

**Comment by AIGRIND-LLC** [comment]
@NathanSweet is there any document describing all changes in state/mixing/timelines workflow since v3.5?

**Comment by badlogic** [comment]
We don't have a sort of diff. However, AnimationState itself has no API changes, only additions (setEmptyAnimation/addEmptyAnimation), and the revised `TrackEntry` class is fully documented here http://esotericsoftware.com/spine-api-reference#TrackEntry

**Comment by badlogic** [comment]
@Fraggle I'm closing this out now. Please get back to us once you've tried the latest and greatest and your issue is not resolved.

**Comment by Fraggle** [comment]
Hello,

Well, I overrided trackEnd to max float on friday and then you did it yourself :)
It does fix most of my issues, thanks.
(i have another one but I'll open another issue for it)
