### ISSUE TITLE
[c] Complete event of the old trackEntry sometime trigger after a Start event for the a new trackEntry on the same trackIndex.

### ISSUE THREAD

**Issue by Fraggle** [EsotericSoftware/spine-runtimes#795]
Hi,

I can't pinpoint exactly how to reproduce it 100% but it happens quite often nonetheless.
I have a sequence "idle_X" on trackIndex 0 set to play but not loop.
I have a complete listener and when the "idle_X" sequence complete I put start another one immediately (i have several idle animations that's why I don't use looping).
Sometime, another animation will be started on trackIndex 0 and will interrupt the idle sequence.
As I should not receive a "complete" event for the idle sequence, it should let the new animation play.
However, sometimes, I still receive the complete event of the idle animation just after getting the start event of the new animation.
I have read this [in the forum](http://fr.esotericsoftware.com/forum/Start-Complete-and-End-event-7385?sid=0c356b018024aa005ba1225f0805831e) but i'm not sure it relate since I'm talking about complete and not end.

Thanks,

Seb

**Comment by badlogic** [comment]
When you set or add a new animation, the state of the current track entry (holding the data for the current idle animation) is not immediately update. This happens in the next `spAnimationState_apply` (and `spAnimationState_applyMixingFrom`) call.

The order of events to expect is as follows when you set a new animation on a track (without calling spAnimationState_update/apply yet):

1. A dispose event for all queued animations on the track that haven't been played yet.
2. An interrupt event for the currently played track entry that's being interrupted (your idle sequence), unless it wasn't yet applied.
3. A start event for the new animation track entry

The old track entry will become the `mixingFrom` entry on the new track entry of the new animation. When you then call `spAnimationState_update` the `mixingFrom` entry representing your idle animation will get updated with the delta time you pass in.

If the mixing duration you set between the idle and new animation is larger then the remaining time on the idle animation, then you will get a complete event for the idle animation in `spAnimationState_queueEvents` which is called by `spAnimatinState_apply`.

This actually works as intended: if the `mixingFrom` animation you are about to replace completes before the mixing duration is over, it makes sense to fire a complete event.

This would also explain why you can't reproduce it reliably. It only happens if the remaining animation time on the idle entry is smaller than the mixing duration.

You could set the mixing duration to 0 to test this theory, you should never get a complete event then.

You can query the track in the complete listener and see if there's an idle animation queued up or a "normal" animation. In the latter case, don't enqueue an idle animation.

Let me know if that works for you.

**Comment by Fraggle** [comment]
I'll have to check but i think my mixing is already set to 0.

**Comment by Fraggle** [comment]
Hello,

I'm sorry but, unless I'm missing something, I checked and my mixDuration is set to 0 (the default).
From what I understand from the code, it seems that there is a one frame delay no matter what :
```
if (entry->mixDuration == 0) /* Single frame mix to undo mixingFrom changes. */
	mix = 1;
else {
	mix = entry->mixTime / entry->mixDuration;
        if (mix > 1) mix = 1;
}
```

Am I wrong ?

Thanks,

Seb

**Comment by NathanSweet** [comment]
Even with a 0 `mixDuration`, after setting the new animation, the old animation needs one more frame to be mixed out. This is how the old animation is reset to the setup pose. Here's how to reproduce your problem:
```
state.addListener(new AnimationStateAdapter() {
	public void complete (TrackEntry entry) {
		System.out.println(entry + " complete");
		System.out.println("current: " + state.getCurrent(0));
		System.out.println("setAnimation: walk 2");
		state.setAnimation(0, "walk", false);
	}
});

System.out.println("frame 1");
System.out.println("setAnimation: walk 1");
state.setAnimation(0, "walk", false);
state.update(0.79f); // walk duration is 0.8
state.apply(skeleton);

System.out.println("frame 2");
System.out.println("setAnimation: jump");
state.setAnimation(0, "jump", false);
state.update(0.02f);
state.apply(skeleton);
```

Output:
```
frame 1
setAnimation: walk 1
frame 2
setAnimation: jump
walk complete
current: jump
setAnimation: walk 2
```

It makes sense not to notify listeners for `event` or `complete` events when `mixDuration` is 0. There is still a 1 frame mix out, but it's not a mix the user explicitly requested.
