### ISSUE TITLE
[cocos2d-x] addEmptyDuration with delay does not work

### ISSUE THREAD

**Issue by chriship** [EsotericSoftware/spine-runtimes#820]
If I set the delay to 0 when I call addEmptyAnimation it does not work. I would expect it to stop the animation immediately but it does not.

This does not work:
`anim3->addEmptyAnimation(0, 0, 0);`

This does work:
`anim3->addEmptyAnimation(0, 0, 1);`

**Comment by badlogic** [comment]
What default mix time did you set? Even with a 0 second delay, the underlying animation state will still mix the previous animation with your empty animation for the mix time duration.

**Comment by chriship** [comment]
I'm not sure what you mean? 
The mix duration is 0.
I didn't use setMix to set a default mix time (can you do that with an empty animation)?

**Comment by badlogic** [comment]
Sorry, I forgot the second parameter of `addEmptyAnimation` specifies the mix time, which in your case is `0`. I'll try to reproduce this with our cocos2d-x sample unless you have a reproduction case for me.

**Comment by badlogic** [comment]
So, after some investigation, here's the final verdict. This is working as designed for the time being. Adding an animation with a delay of 0 means "play this animation after the last animation is done". You can use `setAnimation` instead of `addAnimation` to achieve what you want to do, or alternatively pass a tiny delay > 0 to `addAnimation`. The code responsible for this behaviour is here: https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-c/spine-c/src/spine/AnimationState.c#L648
