### ISSUE TITLE
Add API to create combined skin from multiple other skins

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#841]
### Mix & Match
A project contains multiple skins, one for each part of a character, e.g. 

- boot_chucks
  - boot_chucks_ankle_left
  - boot_chucks_feet_left
  - boot_chucks_ankle_right
  - boot_chucks_feet_right
- eyes_blue
  - eye_blue_left
  - eye_blue_right

At runtime, a user should be able to select specific parts, e.g. chucks + blue eyes, to customize their character. The user should thus be able to create a new custom skin, merge the attachments from the partial skins, and set that custom skin on the skeleton.

### Custom attachments & regions
Users should be able to add their own custom attachments, potentially (deep) copied from existing attachments, and manipulate the regions of `RegionAttachment` and `MeshAttachment`

### Override default skin
Scenario: the default skin has a head attachment for some slot. Another skin to be set active does not have an attachment for that slot, so at rendering time we fall back to default skin head attachment. Now the user wants to not display the head, and effectively override the default skin. The only way to achieve this is to remove the attachment from the default skin.

We will not provide a solution for this programmatically, as the problem lies in the setup of the skeleton's skins. The default skin should not have the head attachment in it in the first place. Instead, the head should be part of the non-default skin(s).

### `setSkin` should remove attachments not in new skin
Currently, when switching from one skin to another, attachments of the old skin that are not in the new skin remain visible (assigned to their slot). This behaviour should be changed to remove all old skin attachments. See https://github.com/EsotericSoftware/spine-runtimes/issues/506

### active skin A doesn't have attachment X, animation or `setSlotsToSetup` sets attachment X, skinB with attachment X is set, nothing is shown
This case can be solved by either applying the animation with the attachment timeline responsible for making X visible, or by calling `setSlotsToSetupPose`. The alternative is to add the placeholder name to a slot when setting a null attachment, which introduces allocation problems and complicates the API a little.

### Don't remove manually set attachments if setting a skin
This is already the case, only attachments from the old skin that are also in the new skin will get replaced.

## API changes & additions
The API should allow merging (a subset of) attachments from multiple skins into a new, temporary, skin. Pseudo code:

```java
Skin customSkin = new Skin("customSkin");
Skin bootsChucks = skeleton.getData().findSkin("boots_chucks");
Skin eyesBlue = skeleton.getData().findSkin("eyes_blue");

// merge in all attachments from the other skin
customSkin.setAttachmentsFromSkin(bootsChucks);
customSkin.setAttachmentsFromSkin(eyesBlue);

// add a single attachment (previously, addAttachment)
customSkin.setAttachment(slotIndex, name, attachment)

// remove a single attachment
customSkin.removeAttachment(slotIndex, name);

// remove all attachments in the skin
customSkin.removeAll();

// Set the new skin
skeleton.setSkin(customSkin);
skeleton.setSlotsToSetupPose();
```
`addAttachment` gets renamed to `setAttachment` as it better reflects the semantics.

`setSkin` removes all old attachments, and sets only the new attachments for which there was an old attachment in place. Subsequent calls to ``setSlotsToSetupPose` or applying the current animation which may have attachment timelines will ensure that all required attachments are visible.

To facilitate **deep copies of skins**, attachments must be able to return a copy of themselves. For the reference implementation, we introduce a **copy constructors** for all attachment types, with similar implementations in other runtimes. We can then add `Skin#copyAttachmentsFromSkin()`, which will add copies of all attachments in the provided skin to this skin. User can then manipulate the copied attachments. 

In addition, we should **expose the `region` fields** in `RegionAttachment` and `MeshAttachment` in a way that lets users completely customize the attachment. **Note:** attachment deep copies will **not** deep copy the associated GPU/engine specific resources, e.g. textures!

For runtimes with **manual memory management**, the custom skin needs to be deallocated manually by the user. If the skin is a shallow copy, referencing attachments of another skin, deallocating the skin must not deallocate the referenced attachments (see #991). We may have to introduce an ownership concept to attachments. There are three scenarios:

1. Attachments in a skin are owned by the skin
2. Attachments in a skin are owned by (an)other skin(s)
3. Attachments in a skin are owned by the skin and by (an)other skin

Scenario 1 is the current implementation. Manually memory managed runtimes like spine-c will thus deallocate the attachments of a skin when deallocating a skin. For scenario 2 we can introduce a second deallocation function for skins that allows the user to specify whether to deallocate attachments as well when deallocating the skin. For scenario 3, users need to track ownership, invoke deallocation functions accordingly (e.g. remove all referenced shallow copied attachments, then dispose the skin which will also dispose the remaining deep copied attachments).

## Final API changes
- Rename `Skin#addAttachment` to `Skin#setAttachment` to better reflect semantics
- Add `Skin#removeAttachment(index, name)` (already in reference implementation)
- Add `Skin#clear()`, convenience method to remove all attachments if one does not want to instantiate a new skin
- Add `Skin#setAttachments(Skin)`, which copies the references of all attachments from the `other` skin to `this` skin. 
- Add `Skin#copyAttachments(Skin)`, which makes a deep copy of all attachments from the `other` skin and adds them to `this` skin.
- Add `Attachment#copy()` which creates a deep copy of the attachment, except for the rendererObject, which is shallowly copied.
- Add `ObjectSet<SkinEntry> Skin#getEntries()`, copies internal keys.

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua
- [x] spine-love
- [x] spine-corona

---
- [x] Update runtimes guide & reference

Additional porting needed for:

https://github.com/EsotericSoftware/spine-runtimes/commit/eae88a058cd3ee990f462284361d10388b824675
https://github.com/EsotericSoftware/spine-runtimes/commit/b87ff7337bc427c4cce6b0d923f1f3f81ef9dff4
https://github.com/EsotericSoftware/spine-runtimes/commit/47c3704acdde96d00d44bf5bfe42b4cc15d6affe
https://github.com/EsotericSoftware/spine-runtimes/commit/8d0ffd08f070b89e4758cc5e23261e388fd0a5b6
https://github.com/EsotericSoftware/spine-runtimes/commit/829fcc416887e1df1360edc8ca27bc3271fb2e75

**Comment by pharan** [comment]
My recommended additions and changes to the Skin API:

`Skin.add(Skin otherSkin)`
adds attachments from another skin (mentioned above as "addAttachmentsFromSkin"

`Skin.removeAttachment(int slotIndex, String name)`
for removing attachments from the dictionary. This is required because the current system does not allow you to set a key to null. This is also important for allowing the lookup to fallback to the default skin.

Rename `addAttachment` to `setAttachment` to clarify that existing entries can be overwritten.

Maybe add overloads for `setAttachment` and `removeAttachment` with a `Skeleton` param so the user can set values by slot name rather than slot index.

Allow entries that return null.
Skins currently have null fallback behavior.
`skeleton.getAttachment` uses skeleton.skin, and if that returns null, it uses skeleton.data.defaultSkin.
This means you cant set a slot to be empty if the base/default skin defines it.
For example, at runtime, to customize an instance of a skeleton to be headless, you can't just null the "head" entry on the skin.

Get deep and shallow copies of the skin.
Shallow copy so the user can just pick and choose existing attachments without creating new attachment objects.
Deep copy so the user can remap attachments, create their own linked meshes mapped to their own textures.

And in the context of the above, allow cloning of all attachment types, and setting their region. This is so users can also clone and re-texture copies of existing skins, or make their own linked meshes with different textures.

All these cases are especially needed/problematic where the attachments and skins are built in code/at runtime/with game editors rather than in Spine.

**Comment by pharan** [comment]
Good docs.

"DEEP COPY"
Sorry, just read my old post again. For "deep copy" here, I guess I just meant copy-constructors for attachment types, which we don't have officially.
This is for when users need to make remapped versions of attachments/new linked meshes individually.
I think spine-libgdx used to have copy constructors but they were really just for the editor.

The case where you create new copies of all of a skins' elements is useful for repacking though, which is useful in Unity because it works around certain limitations of their built-in systems. Not sure if it makes sense in other runtimes.

"EMPTY ATTACHMENT"
I like it.

We should probably also have skin.clear() ?

**Comment by pharan** [comment]
Is this going to be applied to 3.7 or 3.6?

**Comment by NathanSweet** [comment]
Since 3.7 has the `Skins` view, it might be nice to squeeze this into 3.7.

**Comment by NathanSweet** [comment]
spine-libgdx in 3.6 has had Skin#addAttachments(Skin) for a while now:
https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/Skin.java#L67

Forum user who wants to combine skins:
http://esotericsoftware.com/forum/Multiple-skins-approach-10930?p=49250#p49250

**Comment by pharan** [comment]
esotericsoftware.com/forum/Unity-spine-unity-3-7-problems-with-SetSkin-10994

**Comment by NathanSweet** [comment]
FWIW, spine-libgdx in 3.7 has Skin#removeAttachment.

**Comment by NathanSweet** [comment]
Punting to future release (sorry).

**Comment by pharan** [comment]
User reported problem: http://esotericsoftware.com/forum/Color-Change-11185
Case:
User does customization through mixing and matching skins, but also by changing the colors of the slots.

Problem:
Since updating a skeleton instance's attachments using a newly set skin currently requires calling `Skeleton.setSlotsToSetupPose` and `AnimationState.apply(skeleton)`, it has a sideeffect of wiping out all custom slot colors.

Possible solutions;
a. Add `Skeleton.setSlotAttachmentsToSetupPose` method so it doesn't reset slot colors.
b. User should reapply all the colors to all the slots every time setSlotsToSetupPose is called.

**Comment by NathanSweet** [comment]
@pharan In that case I think it's reasonable for a user to set the slot attachments rather than use `setSlotsToSetupPose`. For each slot:
```
slot.setAttachment(null);
if (slot.data.attachmentName != null) {
	slot.setAttachment(slot.bone.skeleton.getAttachment(slot.data.index, slot.data.attachmentName));
}
```
You're right we could provide `setSlotAttachmentsToSetupPose`. I have mixed feelings about providing a convenience method for many different, simple actions, but on the other hand Slot `setToSetupPose` only does two things: sets the color and the attachment.

**Comment by pharan** [comment]
I share the hesitation. But I think expecting them to essentially know how to write `setSlotAttachmentToSetupPose` themselves and do it adds quite a bit friction.

**Comment by NathanSweet** [comment]
Aye, depends on how common it is to be worth cluttering our API. The way they'd figure it out is tracing Skeleton `setSlotsToSetupPose`, then they'd copy Slot `setToSetupPose` and omit changing the color.

**Comment by HaraldCsaszar** [comment]
Note: above commit 1d0cce3 is incorrectly referencing this issue ticket instead of #1346
