### ISSUE TITLE
[ue4] Packaging fails on Windows

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#850]
See http://esotericsoftware.com/forum/UE4-is-such-a-good-toolkit-its-amazeballz-7975

**Comment by NexusEast** [comment]
I found problems.
These errors generated because following functions declared or implemented in wrong place.
Their declarations are outside of macro **WITH_EDITORONLY_DATA** while implemented inside it.
The functions are:

_USpineSkeletonDataAsset::BeginDestroy(void)
USpineAtlasAsset::BeginDestroy(void)
USpineSkeletonDataAsset::GetSkeletonData(struct spAtlas *,bool)
USpineSkeletonDataAsset::GetAnimationStateData(struct spAtlas *)
USpineAtlasAsset::GetAtlas(bool)_

Since I don't know what are they actually do, so I have no idea whether put them all inside or 
outside the macro.

Hope this information helps.

**Comment by badlogic** [comment]
This is fixed in the 3.6-beta branch now. Note that you need to export from the 3.6-beta editor to use the 3.6-beta runtime. You can also just look at the diff and apply it to your local copy until we release 3.6.
