### ISSUE TITLE
[skeletonviewer] need instructions on running from source (Spine 2.x)

### ISSUE THREAD

**Issue by tayl0r** [EsotericSoftware/spine-runtimes#882]
I'm trying to run the skeleton viewer from source (because I want to run a way older version, one that supports Spine.app 2.1.27 (latest 2.x version) and spine runtime as of commit c31b2e4 (July 17, 2015)).

So, I see the SkeletonViewer.java file. Lets try to compile it:

javac SkeletonViewer.java
> missing dependencies

Ok, seems like I need to build this with Eclipse. I start Eclipse and import the spine-libgdx and spine-skeletonviewer projects, but they won't build because it's missing the "gdx", "gdx-backend-lwjgl" and box2d libraries. I'm not sure how to add these libraries. It seems like the build system is supposed to grab them automatically but it isn't.

Please assist!

**Comment by badlogic** [comment]
Hi Taylor!

Running the SkeletonViewer from source is a bit complicated. You have to also clone https://github.com/libgdx/libgdx and import those into your Eclipse workspace. You only need "gdx-jnigen", "gdx", "gdx-backend-lwjgl" and "gdx-box2d". You will also have to make sure you use a libgdx commit at around the same time as 2.1.27 was released, as SkeletonViewer users libgdx's scene2d which has since evolved as well.

Let me know if that doesn't work for you.
