### ISSUE TITLE
[runtime] Unity runtime can not load animations exported with Dragonbones

### ISSUE THREAD

**Issue by HotkeyM** [EsotericSoftware/spine-runtimes#933]
I tried to export animation with with Dragon bones PRO 5.2 File->Export, Type = Spine, Data Version = 3.3 to import with Spine runtime for Unity claimed to support 3.3 version.

First, it failed to import because original Spine format header has "skeleton":{"hash":"your hash there"} section. I commented that checking, but Spine runtime still continued to raise exception. It also fails on the first animation loading with exception, with KeyNotFoundException.

**Comment by badlogic** [comment]
Sorry you've been duped by DragonBones. Spine is not associated with DragonBones in any way. Their export functionality is their responsibility. We do not support DragonBones ourselves, at all. 

Also, if you use the Spine Runtimes, you must have a valid Spine license. DragonBones should make that clear, otherwise their users are in legal trouble if they use the Spine Runtimes without a valid Spine license.
