### ISSUE TITLE
Investigate C++11 runtime

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#981]
While our spine-c runtime is pretty good, it is still cumbersome to use from within C++. Ideally, we'd have a C++11 based runtime compatible with as many platforms as the C89 based runtime.

- [ ] Define platforms to support
- [ ] Check C++11 support of toolchains for each platform
- [ ] Come up with C++11 coding subset and standard that works on each platform
- [ ] Implement runtime is subset is "good enough" and actually a win over C89

**Comment by ghost** [comment]
I'm currently integrating the spine-c runtime into my C++03 game framework now, which targets Windows 7+, Mac OS X 10.8+, iOS 8.0+, UWP 10, and Android 16+. I plan on leveraging rapidjson to handle file loading since it is already being used in my framework. I'm thinking I will be porting the whole c runtime into a C++ runtime for my use.

Just thought I would bring this up, though it sounds like you are wanting to target C++ 11 explicitly, I will be checking in on this issue periodically.

**Comment by badlogic** [comment]
I'm not hellbound on needing C++11 features, C++03 may suffice. From what I read so far, C++03 may be the only thing that is also guaranteed to work on consoles. We don't have access to any console SDKs, so can't confirm this atm.

**Comment by ghost** [comment]
Then in that case, I might have a PR for you pretty soon, since I plan on having my C++03 implementation completed here in a few days.

**Comment by badlogic** [comment]
@sgowen that sounds great! To merge the PR and integrate your contribution into our repo, we need you to sign our [CLA](http://esotericsoftware.com/files/cla.txt) and have it sent to contact@esotericsoftware.com. Sorry for the red tape :/

**Comment by ghost** [comment]
@badlogic No worries! We'll discuss once I get the PR ready.

**Comment by badlogic** [comment]
Results of my investigation.

# Target platforms & Tool support
We aim at Windows, Linux, macOS, Android, iOS, WebAssembly as well as consoles. C++11 is supported on the first 5 platforms to the extend we'd need it for a spine-cpp platform. For consoles, the information is sparse, but from my research it appears that at least C++03 is supported.

# C++ Subset
I'm a strong believer in Branimir's [Orthodox C++](https://gist.github.com/bkaradzic/2e39896bc7d8c34e042b#file-orthodoxc-md). This will increase compatibility and guarantee that we don't fall into the "OMG, need to use all the shiny features" trap.

There are two areas that need some thought:

* Collections: STL has been a major source of pain throughout the years, so we'll avoid that. Instead, we will create our own simple collections. The Spine API thankfully can live with just dynamic arrays, which makes life easier.
* Callbacks: We could use some C++11 features to make this a bit more powerful. Due to compatibility concerns, we should stick to plain old C function pointers, with overloads (hidden behind #define checks) for C++11, so proper closures can be passed.

@sgowen I'm closing this out for now, as the initial goal of investigating the issue is complete. I'm looking forward to a PR of yours!

**Comment by ghost** [comment]
@badlogic Sounds good! Yeah, I should have it ready sometime this week!

For the most part, I'm more a fan of KISS (Keep it Simple Stupid) than Orthodox C++. Though there does seem to be some overlap. That being said, writing C code in a C++ context just for the sake of doing so unless you cannot (as Orthodox C++ would suggest) seems silly to me. C++ is different, and has a different way of doing things. I think we should embrace that. C++ has its issues, but reverting back to C-style code seems counter-productive.

I try write my C++ code to be as portable as possible, but typically I don't mind using STL if I am able to personally see it in action on each platform I am targeting. That being said, right now in spine-cpp, I am only using std::vector and std::unordered_map. I accept that spine-cpp will have a much wider platform audience than what I am used to (namely, WebAssembly and Consoles), so I'll replace these with dynamic arrays before my PR.

A few things I strive by when writing C++.

1. Don't use Boost, EVER.
2. If you need RTTI, roll your own (much faster, and you control which classes participate)
3. Don't use exceptions
4. Keep all implementation details inside cpp files. The only braces I want to see in header files are for opening/closing namespaces, classes, structs, and enums.
5. Initialize everything in the constructor via initialization lists (so that objects aren't constructed twice)
6. Always use pre-increment versus post-increment
7. Always pass by const Reference or Reference (don't intentionally infect the codebase with const if it is unnecessary)
8. Don't use multiple inheritance
9. More stuff I'm probably forgetting

**Comment by badlogic** [comment]
I agree with everything you said :) Orthodox C++ was just the only public
doc I knew that summarizes most of my own thoughts. If you look at
Branimir's bgfx, you'll see he's not using all that much C design himself.

Looking forward to your PR!

**Comment by ghost** [comment]
Just wanted to provide a quick update. Should be just a few more days. Had to go through the codebase and rip out std::map and std::vector in favor of portable hand-written ones. That was fun! And I'm glad I did it.

**Comment by ghost** [comment]
@badlogic I just realized I never printed out and signed the CLA, so I'm doing that now, and will send it to the email you listed above.

**Comment by badlogic** [comment]
Hah, I forgot too! I'm going to merge this on monday on the 3.7-beta branch
and start rewiring all but the SFML backend to use the C++ runtime instead
of the C runtime.
