### ISSUE TITLE
Humor: Order of elements in affine matrix

### ISSUE THREAD

**Issue by ivanpopelyshev** [EsotericSoftware/spine-runtimes#997]
![OMG](https://sun9-3.userapi.com/c840137/v840137965/2566b/iTt8D53fbrY.jpg)

You guys use "adobe russian l10n" order in spine-ts. It differs from matrices in Pixi, Flash and even apple Swift.

**Comment by pharan** [comment]
That's funny.

I've never seen people order it the way it says in the EN docs.
I learned it in school/books, and in various tutorials and videos on the internet as:
```
a  b
c  d
```
'cause the rote memorized formula was always
`ax + by`
`cx + dy`

I can't find the Swift docs that show it as you described though. That would be funny.

**Comment by ivanpopelyshev** [comment]
the idea is that you have three vectors: Axis X (a,b) , Axis Y (c,d) and offset (tx, ty), that's three columns :) In your case its two rows and one column which is kinda strange.:

```
ax + by + tx
cx + dy + ty
```

**Comment by pharan** [comment]
It's hackish but also pretty standard and common.
What it's doing is actually using 3D skew to represent 2D translation.
In the same way, 3D engines would use a 4x4 matrix, using 4D skew to represent a 3D translation.
I imagine it's done this way because it's more efficient on the GPU where the full-on matrix computations would fit right in.

At least, that's what I understand of it.

Spine code just does it the overt, non-hackish way. Mostly because it's CPU/main memory stuff, I guess. I'm not sure if the order of operations or translate space works out the same.

**Comment by ivanpopelyshev** [comment]
@pharah its strange because (a,b) is a row, but (tx, ty) is a column :))) As for general knowledge, I even know how to make perspective with only 3x3 matrix (https://github.com/pixijs/pixi-projection)

Also we are uploading data in gpu by columns.

**Comment by badlogic** [comment]
This is a humour free zone! :)
